#!/usr/bin/env python3
"""Run the official pseudocode conversion logic and emit provenance sidecars."""

import argparse
import contextlib
import importlib.util
import io
import json
import os
import re
import shutil
from pathlib import Path

from config import CHAPTER_STEMS, GENERATED_FILES, ROOT


def load_snarf():
    path = ROOT / "scripts/vendor_compat/snarf_python3.py"
    spec = importlib.util.spec_from_file_location("snarf_python3", path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(module)
    return module


def transform_line(module, line: str) -> list[str]:
    out = io.StringIO()
    err = io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        module.snarf(io.StringIO(line))
    return out.getvalue().splitlines()


def build_chapter(module, latex_dir: Path, stem: str, output_dir: Path, map_dir: Path) -> None:
    source = latex_dir / f"{stem}.tex"
    destination = output_dir / f"{stem}-python.tex"
    header = ["%%%", "%%% Autogenerated file - do not edit ", "%%%"]
    output_lines: list[str] = []
    mapping: list[dict] = []
    logical = header + source.read_text(encoding="utf-8").splitlines()
    for position, line in enumerate(logical):
        original_line = 0 if position < 3 else position - 2
        emitted = transform_line(module, line)
        for text in emitted:
            output_lines.append(text)
            mapping.append(
                {
                    "generated_line": len(output_lines),
                    "original_file": f"{stem}.tex",
                    "original_line": original_line,
                    "kind": "generated_header" if original_line == 0 else (
                        "code_import_expansion"
                        if line.startswith(("\\codeimport", "\\pcodeimport"))
                        else "transformed_source"
                    ),
                    "import_command": line if line.startswith(("\\codeimport", "\\pcodeimport")) else None,
                }
            )
    destination.write_text("\n".join(output_lines) + "\n", encoding="utf-8")
    (map_dir / f"{stem}-python.map.json").write_text(
        json.dumps(mapping, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def build_main(latex_dir: Path, output_dir: Path, map_dir: Path) -> None:
    source = latex_dir / "ods.tex"
    lines = ["%%%", "%%% Autogenerated file - do not edit ", "%%%"] + source.read_text(
        encoding="utf-8"
    ).splitlines()
    output = []
    mapping = []
    replacement = (
        r"\newcommand{\javaonly}[1]{}\newcommand{\cpponly}[1]{}"
        r"\newcommand{\pcodeonly}[1]{#1}\newcommand{\notpcode}[1]{}"
        r"\newcommand{\lang}{pseudocode}"
    )
    for index, line in enumerate(lines, 1):
        transformed = line.replace("-lang", "-python")
        if "%HEADCOMMAND" in transformed:
            transformed = transformed.replace("%HEADCOMMAND", replacement)
        output.append(transformed)
        mapping.append(
            {
                "generated_line": index,
                "original_file": "ods.tex",
                "original_line": 0 if index <= 3 else index - 3,
                "kind": "generated_header" if index <= 3 else "transformed_source",
                "import_command": None,
            }
        )
    (output_dir / "ods-python.tex").write_text("\n".join(output) + "\n", encoding="utf-8")
    (map_dir / "ods-python.map.json").write_text(
        json.dumps(mapping, indent=2) + "\n", encoding="utf-8"
    )


def preprocess(source_root: Path, work_dir: Path) -> None:
    latex_dir = source_root / "latex"
    output_dir = work_dir / "generated"
    map_dir = work_dir / "maps"
    output_dir.mkdir(parents=True, exist_ok=True)
    map_dir.mkdir(parents=True, exist_ok=True)
    module = load_snarf()
    previous = Path.cwd()
    os.chdir(latex_dir)
    try:
        build_main(latex_dir, output_dir, map_dir)
        for stem in CHAPTER_STEMS:
            build_chapter(module, latex_dir, stem, output_dir, map_dir)
    finally:
        os.chdir(previous)
    actual = sorted(p.name for p in output_dir.iterdir())
    if actual != sorted(GENERATED_FILES):
        raise RuntimeError(f"unexpected generated set: {actual}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_root", type=Path)
    parser.add_argument("work_dir", type=Path)
    args = parser.parse_args()
    preprocess(args.source_root, args.work_dir)


if __name__ == "__main__":
    main()
