"""生成 2026 版 408 数据结构全部考纲叶子条目的知识 authoring 输入。

该脚本把公开考纲的 56 个叶子条目展开为可独立检索的原子知识点，并生成：
- 七个内容章节的 taxonomy；
- 结构化来源记录、计划、草稿和可视化候选；
- “考纲条目 → concept_id”零缺口覆盖清单；
- 来源指纹与外部复核入口。

所有新知识点保持 review_pending；脚本本身不宣布内容审查通过。
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

from knowledge_base.scripts.kb_pipeline.io_utils import (
    read_json,
    write_json_atomic,
    write_jsonl_atomic,
)


ROOT = Path(__file__).resolve().parents[2]
COURSE_ID = "cs408-data-structures"
REPORT_SHA256 = "566c0b77294c128fa963dabbc08516e002f8feab92858c9c99d2c1c15b67bdcc"
SOURCE_URLS = [
    "https://www.moe.gov.cn/s78/A15/s8355/moe_782/tnull_21964.html",
    "https://www.kmxwd.com/uploads/images/20251015/68eef5daf0564.pdf",
    "https://www.tup.com.cn/bookscenter/book_09892801.html",
]

VISUALIZATION_BINDINGS = {
    "cs408-recursion-call-stack": ["call-stack.factorial-recursion.v1"],
    "cs408-sequential-list-insert-delete": ["ods.arraystack-insertion.v1"],
    "cs408-circular-queue-representation": ["ods.arrayqueue-representation.v1"],
    "cs408-circular-queue-state": ["ods.arrayqueue-representation.v1"],
    "cs408-binary-tree-depth-traversals": ["cs408.binary-tree-traversal.v1"],
    "cs408-binary-tree-level-order": ["cs408.binary-tree-traversal.v1"],
    "cs408-depth-first-search": ["cs408.graph-traversal.v1"],
    "cs408-breadth-first-search": ["cs408.graph-traversal.v1"],
    "cs408-graph-traversal-complexity": ["cs408.graph-traversal.v1"],
    "cs408-binary-search": ["cs408.binary-search.v1"],
    "cs408-binary-search-decision-tree": ["cs408.binary-search.v1"],
    "cs408-avl-rotations": ["cs408.avl-rotation.v1"],
    "cs408-avl-updates": ["cs408.avl-rotation.v1"],
    "cs408-kmp-prefix-function": ["cs408.kmp-matching.v1"],
    "cs408-kmp-matching": ["cs408.kmp-matching.v1"],
    "cs408-next-nextval": ["cs408.kmp-matching.v1"],
    "cs408-quick-partition": ["cs408.quick-sort-partition.v1"],
    "cs408-quick-sort-analysis": ["cs408.quick-sort-partition.v1"],
}


OFFICIAL_ITEMS: list[tuple[str, str]] = [
    ("basic-data-structure", "数据结构的基本概念"),
    ("basic-algorithm", "算法的基本概念"),
    ("linear-list-concept", "线性表的基本概念"),
    ("linear-list-sequential", "线性表的顺序存储"),
    ("linear-list-linked", "线性表的链式存储"),
    ("linear-list-applications", "线性表的应用"),
    ("stack-queue-concept", "栈和队列的基本概念"),
    ("stack-queue-sequential", "栈和队列的顺序存储结构"),
    ("stack-queue-linked", "栈和队列的链式存储结构"),
    ("multidimensional-array-storage", "多维数组的存储"),
    ("special-matrix-compression", "特殊矩阵的压缩存储"),
    ("stack-queue-array-applications", "栈、队列和数组的应用"),
    ("tree-concept", "树的基本概念"),
    ("binary-tree-properties", "二叉树的定义及主要特性"),
    ("binary-tree-storage", "二叉树的顺序存储和链式存储"),
    ("binary-tree-traversal", "二叉树的遍历"),
    ("threaded-binary-tree", "线索二叉树的基本概念和构造"),
    ("tree-storage", "树的存储结构"),
    ("forest-conversion", "森林与二叉树的转换"),
    ("tree-forest-traversal", "树和森林的遍历"),
    ("huffman", "Huffman 树和 Huffman 编码"),
    ("disjoint-set", "并查集及其应用"),
    ("heap", "堆及其应用"),
    ("graph-concept", "图的基本概念"),
    ("graph-adjacency-matrix", "邻接矩阵"),
    ("graph-adjacency-list", "邻接表"),
    ("graph-multilist-orthogonal", "邻接多重表和十字链表"),
    ("graph-dfs", "深度优先搜索"),
    ("graph-bfs", "广度优先搜索"),
    ("minimum-spanning-tree", "最小生成树"),
    ("shortest-path", "最短路径"),
    ("topological-sort", "拓扑排序"),
    ("critical-path", "关键路径"),
    ("search-concept", "查找的基本概念"),
    ("sequential-search", "顺序查找法"),
    ("block-search", "分块查找法"),
    ("binary-search", "折半查找法"),
    ("binary-search-tree", "二叉搜索树"),
    ("avl-tree", "平衡二叉树"),
    ("red-black-tree", "红黑树"),
    ("b-tree-b-plus-tree", "B 树及其基本操作、B+ 树的基本概念"),
    ("hash-table", "散列表"),
    ("string-pattern-matching", "字符串模式匹配"),
    ("search-analysis-applications", "查找算法的分析及应用"),
    ("sorting-concept", "排序的基本概念"),
    ("direct-insertion-sort", "直接插入排序"),
    ("binary-insertion-sort", "折半插入排序"),
    ("bubble-sort", "起泡排序"),
    ("selection-sort", "简单选择排序"),
    ("shell-sort", "希尔排序"),
    ("quick-sort", "快速排序"),
    ("heap-sort", "堆排序"),
    ("merge-sort", "二路归并排序"),
    ("radix-sort", "基数排序"),
    ("external-sort", "外部排序"),
    ("sorting-analysis-applications", "排序算法的分析及应用"),
]


def topic(
    slug: str,
    title: str,
    content_type: str,
    question: str,
    summary: str,
    definition: str,
    intuition: str,
    aliases: Iterable[str],
    covers: Iterable[str],
    prerequisites: Iterable[str] = (),
) -> dict[str, Any]:
    return {
        "id": f"cs408-{slug}",
        "title": title,
        "content_type": content_type,
        "question": question,
        "summary": summary,
        "definition": definition,
        "intuition": intuition,
        "aliases": list(aliases),
        "covers": list(covers),
        "prerequisites": list(prerequisites),
    }


CHAPTERS: list[dict[str, Any]] = [
    {
        "id": "408-basic-concepts",
        "title": "Basic Concepts",
        "title_zh": "基本概念",
        "guide_id": "cs408-syllabus-basic-concepts",
        "sections": [
            ("cs408-basic-data-structure", "Data structures", "数据结构基本概念"),
            ("cs408-basic-algorithm", "Algorithms and complexity", "算法与复杂度"),
        ],
        "topics": [
            topic(
                "data-terms",
                "数据、数据元素、数据对象与数据类型",
                "concept",
                "数据、数据元素、数据对象和数据类型分别表示什么？",
                "数据是信息的符号表示，数据元素是基本单位，数据对象是同性质元素的集合，数据类型规定值域与允许操作。",
                "数据是能被计算机处理的符号集合；数据元素是讨论和处理的基本单位，可由若干数据项组成；数据对象是性质相同的数据元素集合；数据类型由取值集合以及作用于该集合的操作共同定义。",
                "像管理学生档案：整批档案是数据，一个学生记录是数据元素，某字段是数据项，同一类学生记录形成数据对象。",
                ["data element", "数据项"],
                ["basic-data-structure"],
            ),
            topic(
                "logical-storage-operations",
                "数据结构的逻辑结构、存储结构与运算",
                "concept",
                "数据结构为什么要同时描述逻辑关系、存储方式和运算？",
                "同一逻辑结构可以有不同存储实现，基本运算的实现与复杂度由具体存储结构决定。",
                "数据结构包含数据元素之间的逻辑关系、这些关系在计算机中的存储表示，以及定义在结构上的运算。逻辑结构回答元素如何关联，存储结构回答关联如何落到内存，运算说明结构允许怎样被访问和修改。",
                "像城市规划同时包含道路关系图、实际道路铺设方式和车辆通行规则，三者缺一不可。",
                ["logical structure", "physical representation"],
                ["basic-data-structure"],
                ["cs408-data-terms"],
            ),
            topic(
                "abstract-data-type",
                "抽象数据类型",
                "concept",
                "抽象数据类型如何把接口语义与具体实现分离？",
                "ADT 用值集合和操作语义描述结构，对外规定能做什么，而不限定内部怎样存储。",
                "抽象数据类型（ADT）由一组数据对象及作用在其上的操作组成，强调操作的输入、输出、前置条件和效果。顺序表与链表可以实现同一线性表 ADT，因为它们对外提供相同语义而内部表示不同。",
                "像同一种自动售货机接口可以由不同机械结构实现，用户只依赖按钮、付款和出货规则。",
                ["ADT", "abstract data type"],
                ["basic-data-structure"],
                ["cs408-logical-storage-operations"],
            ),
            topic(
                "algorithm-characteristics",
                "算法的定义与基本特性",
                "concept",
                "一个过程具备哪些条件才能称为算法？",
                "算法是解决一类问题的有限、确定、可行步骤序列，具有输入、输出并能在有限执行后终止。",
                "算法是对特定问题求解步骤的有限描述。通常要求步骤具有有穷性、确定性和可行性，允许零个或多个输入，至少产生一个输出；同一问题可以有多个正确算法，再按资源成本比较优劣。",
                "像一份可执行菜谱：材料是输入，成品是输出，每一步明确且能实际完成，并且步骤不会无限延续。",
                ["algorithm", "有穷性"],
                ["basic-algorithm"],
            ),
            topic(
                "algorithm-correctness",
                "算法正确性与边界条件",
                "theorem",
                "怎样说明算法对所有合法输入都正确？",
                "正确性要求算法终止，并对每个满足前置条件的输入产生满足后置条件的结果。",
                "算法正确性不能只由少数样例证明。完整论证通常包含：明确输入前置条件与输出后置条件；证明循环不变式或递归归纳关系在初始化、保持和终止时成立；同时检查空输入、最小规模、最大边界和重复元素等特殊情况。",
                "像证明一座桥安全，不能只让几辆车通过，而要说明设计约束在所有允许载荷下都成立。",
                ["correctness proof", "循环不变式"],
                ["basic-algorithm"],
                ["cs408-algorithm-characteristics"],
            ),
            topic(
                "time-complexity",
                "时间复杂度",
                "formula",
                "时间复杂度如何描述算法运行时间随输入规模增长的趋势？",
                "时间复杂度统计基本操作执行次数的渐进增长，而不是依赖某台机器的精确秒数。",
                "设输入规模为 n，把算法中基本操作的执行次数写成 T(n)，再用渐进数量级描述其增长速度。分析时应说明最好、平均或最坏情形；常数因子和低阶项通常在渐进表示中忽略，但循环边界、递归分支和数据分布会改变数量级。",
                "像比较不同路线随城市扩大增加的路程，重点看增长趋势，而不是某次出发遇到的红灯秒数。",
                ["time complexity", "T(n)"],
                ["basic-algorithm"],
                ["cs408-algorithm-characteristics"],
            ),
            topic(
                "space-complexity",
                "空间复杂度",
                "formula",
                "空间复杂度如何衡量算法额外占用的存储量？",
                "空间复杂度描述算法运行所需存储随输入规模的增长，常重点分析除输入本身外的辅助空间。",
                "空间复杂度可包含输入数据、程序常量、辅助变量、动态结构和递归调用栈等存储。比较算法时通常明确报告辅助空间：原地算法只使用常数级额外空间，而递归深度、临时数组或队列可能带来与 n 相关的额外开销。",
                "像搬家时区分原有物品体积和为整理额外租用的周转箱，辅助空间就是这些新增周转资源。",
                ["space complexity", "辅助空间"],
                ["basic-algorithm"],
                ["cs408-algorithm-characteristics"],
            ),
            topic(
                "asymptotic-notation",
                "O、Ω 与 Θ 渐进记号",
                "formula",
                "大 O、大 Ω 和 Θ 分别表达什么渐进界？",
                "O 给渐进上界，Ω 给渐进下界，Θ 同时给出同阶上下界。",
                "若从某个 n 起有 0≤f(n)≤c·g(n)，则 f(n)=O(g(n))；若 f(n)≥c·g(n)，则 f(n)=Ω(g(n))；若同时存在正数 c1、c2 使 c1g(n)≤f(n)≤c2g(n)，则 f(n)=Θ(g(n))。它们描述函数增长界，不等同于最好、最坏情形本身。",
                "像给增长曲线夹上天花板、地板或上下两块夹板，分别对应上界、下界和同阶界。",
                ["Big O", "Big Theta"],
                ["basic-algorithm"],
                ["cs408-time-complexity"],
            ),
            topic(
                "complexity-estimation",
                "循环与递归的复杂度估算",
                "mechanism",
                "怎样从循环或递归结构估算算法复杂度？",
                "顺序语句取最大量级，嵌套循环常相乘，相关循环需精确求和，递归则建立并求解递推式。",
                "分析循环时先确定每层迭代次数和基本操作成本：独立嵌套循环通常相乘，1+2+…+n 这类相关边界需要求和，对数循环来自规模按固定比例缩小。递归算法应写出 T(n) 的递推关系，并同时考虑每层非递归工作和递归树深度。",
                "像核算多层生产线：串联步骤看最重环节，嵌套批次计算总组合数，递归分厂则统计每层分支和层数。",
                ["loop analysis", "recurrence"],
                ["basic-algorithm"],
                ["cs408-asymptotic-notation"],
            ),
        ],
    },
    {
        "id": "408-linear-lists",
        "title": "Linear Lists",
        "title_zh": "线性表",
        "guide_id": "cs408-syllabus-linear-lists",
        "sections": [
            ("cs408-linear-list-basics", "Linear-list basics", "线性表基本概念"),
            ("cs408-linear-list-sequential", "Sequential representation", "顺序存储"),
            ("cs408-linear-list-linked", "Linked representation", "链式存储"),
            ("cs408-linear-list-applications", "Applications", "线性表应用"),
        ],
        "topics": [
            topic(
                "linear-list-definition-operations",
                "线性表的定义与基本操作",
                "concept",
                "线性表的逻辑特征和常用基本操作是什么？",
                "线性表是有限元素序列，除首尾外每个元素有唯一前驱和唯一后继。",
                "线性表 L=(a1,…,an) 表示具有相同数据类型的有限序列。常用操作包括初始化、判空、按位查找、按值查找、插入、删除、求长度和遍历；操作下标的合法范围必须根据查找、插入或删除语义分别判断。",
                "像一列有固定先后顺序的车厢，每节车厢只与前后相邻位置形成线性关系。",
                ["linear list", "List ADT"],
                ["linear-list-concept"],
                ["cs408-abstract-data-type"],
            ),
            topic(
                "sequential-list-storage",
                "顺序表的存储表示",
                "concept",
                "顺序表如何用连续存储单元表示线性表？",
                "顺序表把逻辑相邻元素放在物理连续位置，通过首地址和元素大小直接计算任意元素地址。",
                "若首元素地址为 LOC(a1)、每个元素占 l 个字节，则 LOC(ai)=LOC(a1)+(i-1)l。顺序表通常同时维护当前长度与容量，支持 O(1) 随机访问，但容量固定或扩容时需要重新分配与复制。",
                "像一排连续编号座位，知道起点和座位宽度就能直接算出任意座位的位置。",
                ["sequential list", "顺序存储"],
                ["linear-list-sequential"],
                ["cs408-linear-list-definition-operations"],
            ),
            topic(
                "sequential-list-insert-delete",
                "顺序表的插入与删除",
                "algorithm",
                "顺序表在指定位置插入或删除时为什么需要搬移元素？",
                "插入需把后缀右移，删除需把后缀左移，因此平均和最坏时间为 O(n)。",
                "在位置 i 插入元素前先检查 i 与容量，再从表尾向 i 右移元素后写入新值；删除位置 i 时保存目标，再把 i+1 之后的元素依次左移。移动方向必须避免覆盖尚未搬走的数据，操作完成后更新长度。",
                "像在紧密排队的人群中间加入或移走一人，后面的人必须整体挪动才能保持连续。",
                ["sequential insertion", "sequential deletion"],
                ["linear-list-sequential"],
                ["cs408-sequential-list-storage"],
            ),
            topic(
                "singly-linked-list",
                "单链表的结点与表示",
                "concept",
                "单链表如何用指针连接逻辑相邻元素？",
                "单链表结点保存数据与后继指针，物理位置可以离散，必须从表头沿指针顺序访问。",
                "单链表的每个结点由数据域和 next 指针域组成，头指针标识首结点，可选头结点作为不保存业务数据的哨兵。已知前驱时插入和删除为 O(1)，按位定位仍需从头遍历，时间为 O(n)。",
                "像一串寻宝线索，每张纸保存当前信息和下一张纸的位置，不能按编号直接跳到中间。",
                ["singly linked list", "next pointer"],
                ["linear-list-linked"],
                ["cs408-linear-list-definition-operations"],
            ),
            topic(
                "linked-list-insert-delete",
                "链表结点的插入与删除",
                "algorithm",
                "怎样安全修改链表指针完成插入和删除？",
                "插入先让新结点接上后继再改前驱，删除先保存目标后继再绕过目标，避免断链。",
                "在结点 p 之后插入 s 时执行 s.next=p.next，再令 p.next=s；删除 p 的后继 q 时先令 p.next=q.next，再释放或回收 q。若删除给定结点本身，需要先定位前驱，双链表则可直接利用 prev 指针。",
                "像改接铁路：先把新轨道接到原后续线路，再切换入口；拆轨时先确认绕行线路再断开旧轨。",
                ["linked insertion", "linked deletion"],
                ["linear-list-linked"],
                ["cs408-singly-linked-list"],
            ),
            topic(
                "doubly-linked-list",
                "双链表",
                "concept",
                "双链表为什么能从结点向两个方向移动？",
                "双链表结点同时保存前驱和后继指针，换取反向遍历与已知结点删除的便利。",
                "双链表结点通常含 prev、data、next 三个域。插入或删除会同时修改两侧结点的成对指针，必须保持 p.next.prev=p 和 p.prev.next=p 等局部不变量；其额外空间高于单链表。",
                "像双向列车连接器，每节车厢同时知道前方车厢和后方车厢，换向查看不必从车头重新开始。",
                ["doubly linked list", "prev pointer"],
                ["linear-list-linked"],
                ["cs408-linked-list-insert-delete"],
            ),
            topic(
                "circular-linked-list",
                "循环链表",
                "concept",
                "循环链表如何把表尾与表头连接起来？",
                "循环链表的尾结点不指向空，而指回首结点或头结点，使遍历形成闭环。",
                "单循环链表令尾结点 next 指向首结点，双循环链表还令首结点 prev 指向尾结点。遍历的终止条件应是指针再次到达起点而不是遇到 null，尾指针可让访问表头和表尾都保持常数时间。",
                "像环形跑道没有天然终点，跑一圈后回到起跑线，因此必须记住起点才能判断遍历结束。",
                ["circular linked list", "循环双链表"],
                ["linear-list-linked"],
                ["cs408-singly-linked-list"],
            ),
            topic(
                "linked-list-reversal",
                "单链表原地逆置",
                "algorithm",
                "怎样在线性时间和常数辅助空间内逆置单链表？",
                "遍历时保存后继并逐个反转 next 指针，可在 O(n) 时间、O(1) 辅助空间完成逆置。",
                "维护 prev、cur、next 三个指针：先保存 cur.next，再令 cur.next=prev，随后令 prev=cur、cur=next。循环结束后 prev 成为新表头；若改指针前未保存后继，剩余链表会失去入口。",
                "像沿绳结前进时逐个把箭头反向，但每次必须先记住下一个绳结在哪里。",
                ["list reversal", "三指针逆置"],
                ["linear-list-applications"],
                ["cs408-singly-linked-list"],
            ),
            topic(
                "linked-list-merge",
                "有序链表合并",
                "algorithm",
                "怎样把两个有序链表合并为一个有序链表？",
                "反复比较两表当前首元素并接入较小者，可在 O(m+n) 时间内复用结点完成合并。",
                "使用哨兵结点和尾指针，每次比较两个当前结点的关键字，把较小结点接到结果尾部并推进对应链表；其中一表耗尽后直接接上另一表剩余部分。稳定合并时相等元素应优先取左表。",
                "像两条已按身高排好的队伍合成一队，每次只比较两队最前面的人。",
                ["merge sorted lists", "有序表合并"],
                ["linear-list-applications"],
                ["cs408-singly-linked-list"],
            ),
            topic(
                "sequential-vs-linked",
                "顺序表与链表的选择",
                "comparison",
                "顺序表和链表应如何按访问、更新与空间需求选择？",
                "顺序表随机访问和局部性好，链表动态插删灵活；选择取决于操作比例、容量变化和内存约束。",
                "顺序表按下标访问为 O(1)，但中间插删通常 O(n)，并可能预留容量；链表定位为 O(n)，已知位置附近插删可 O(1)，但每结点需要指针且局部性较差。算法设计应根据主要操作而不是结构名称机械选择。",
                "像固定座位与流动队伍的取舍：前者找位置快，后者调整队形更灵活。",
                ["array vs linked list", "存储结构比较"],
                ["linear-list-applications"],
                ["cs408-sequential-list-storage", "cs408-singly-linked-list"],
            ),
        ],
    },
    {
        "id": "408-stacks-queues-arrays",
        "title": "Stacks, Queues and Arrays",
        "title_zh": "栈、队列和数组",
        "guide_id": "cs408-syllabus-stacks-queues-arrays",
        "sections": [
            ("cs408-stack-basics", "Stacks", "栈"),
            ("cs408-queue-basics", "Queues", "队列"),
            ("cs408-array-storage", "Array storage", "数组与压缩存储"),
            ("cs408-stack-queue-applications", "Applications", "栈和队列应用"),
        ],
        "topics": [
            topic(
                "stack-lifo",
                "栈的 LIFO 语义与基本操作",
                "concept",
                "栈为什么称为后进先出的受限线性表？",
                "栈只允许在栈顶插入和删除，最后压入的元素最先弹出。",
                "栈是只在一端进行插入和删除的线性表，这一端称为栈顶，另一端称为栈底。push 压入元素，pop 删除并返回栈顶，top 只读取栈顶；空栈执行 pop 或 top 必须按接口规则处理下溢。",
                "像一摞盘子，只能从最上面放入或取走，因此最后放上的盘子最先被拿走。",
                ["stack", "LIFO"],
                ["stack-queue-concept"],
                ["cs408-linear-list-definition-operations"],
            ),
            topic(
                "sequential-stack",
                "顺序栈",
                "concept",
                "顺序栈如何用数组和栈顶指针实现 push 与 pop？",
                "顺序栈把元素保存在连续数组中，通过 top 指示栈顶元素或下一空位。",
                "顺序栈使用数组和 top 变量维护有效区间。若 top 表示栈顶下标，空栈常取 -1；若 top 表示下一空位，空栈常取 0。push 前检查上溢，pop 前检查下溢，两种约定都正确但判空、判满公式不能混用。",
                "像一列编号储物格和一个箭头，箭头约定指向最后占用格或下一空格，操作必须始终采用同一种约定。",
                ["array stack", "top pointer"],
                ["stack-queue-sequential"],
                ["cs408-stack-lifo"],
            ),
            topic(
                "linked-stack",
                "链栈",
                "concept",
                "链栈如何把链表表头作为栈顶？",
                "链栈通常在单链表表头执行插入和删除，使 push 与 pop 都为 O(1)。",
                "链栈以 top 指针指向栈顶结点。push 创建新结点并把其 next 指向旧 top，再更新 top；pop 保存 top 数据并让 top 指向后继。只要内存分配成功，链栈不需要预设固定容量，但每个元素有指针开销。",
                "像把新卡片插在卡片链最前面，取出时也只拆最前面的卡片。",
                ["linked stack", "链式栈"],
                ["stack-queue-linked"],
                ["cs408-stack-lifo", "cs408-singly-linked-list"],
            ),
            topic(
                "stack-pop-sequences",
                "合法出栈序列",
                "algorithm",
                "怎样判断给定序列能否由指定入栈顺序产生？",
                "按入栈顺序模拟，无法匹配目标栈顶时继续压栈，若输入耗尽仍不匹配则序列非法。",
                "给定固定入栈序列时，用辅助栈依次压入元素，并在栈顶等于目标出栈序列当前元素时反复弹出。最终目标序列全部匹配才合法。对于 1…n 的入栈顺序，已经被某元素压住且输入位置越过的元素不能越过上层元素先弹出。",
                "像把书依次放进只能从上方取出的箱子，目标取书顺序必须服从上层先离开的限制。",
                ["pop sequence", "栈序列"],
                ["stack-queue-array-applications"],
                ["cs408-stack-lifo"],
            ),
            topic(
                "parentheses-matching",
                "括号匹配",
                "algorithm",
                "栈如何判断多种括号是否正确嵌套？",
                "扫描左括号时入栈，遇右括号时必须与当前栈顶成对，结束时栈应为空。",
                "从左到右扫描字符：左括号压栈；右括号出现时，若栈空或类型与栈顶不匹配则失败，否则弹出栈顶。扫描结束后只有栈为空才全部匹配。时间复杂度 O(n)，辅助空间最坏 O(n)。",
                "像逐层打开盒子必须按相反顺序逐层关上，最近打开的盒子最先闭合。",
                ["parenthesis matching", "括号检查"],
                ["stack-queue-array-applications"],
                ["cs408-stack-lifo"],
            ),
            topic(
                "expression-evaluation",
                "表达式转换与求值",
                "algorithm",
                "栈如何支持中缀、后缀表达式转换与求值？",
                "运算数栈保存数值，运算符栈依据优先级和结合性决定何时弹出计算。",
                "中缀转后缀时直接输出运算数，运算符按优先级、结合性和括号规则进出栈；后缀求值时遇运算数入栈，遇二元运算符依次弹出右、左操作数计算后压回。操作数弹出顺序不能颠倒。",
                "像把待办数字放入材料栈，把运算符按优先级排队，条件成熟时取最近的材料完成一步计算。",
                ["postfix evaluation", "逆波兰表达式"],
                ["stack-queue-array-applications"],
                ["cs408-stack-lifo"],
            ),
            topic(
                "recursion-call-stack",
                "递归与调用栈",
                "mechanism",
                "递归调用为什么天然遵循栈的后进先出顺序？",
                "每次调用保存参数、局部变量、返回地址和执行状态，最深层调用必须先返回。",
                "函数调用会创建活动记录并压入调用栈；递归继续时上一层暂停在调用点。基例结束后，最内层活动记录先弹出并把结果交给调用者，随后逐层恢复。递归深度决定额外栈空间，缺少有效基例会导致栈持续增长。",
                "像进入一串嵌套房间，每进入一间就留下返回路线，离开时只能先退出最后进入的房间。",
                ["call stack", "递归栈"],
                ["stack-queue-array-applications"],
                ["cs408-stack-lifo"],
            ),
            topic(
                "queue-fifo",
                "队列的 FIFO 语义与基本操作",
                "concept",
                "队列为什么称为先进先出的受限线性表？",
                "队列在队尾插入、队头删除，先入队的元素先出队。",
                "队列只允许在一端入队 enqueue，在另一端出队 dequeue；插入端称队尾，删除端称队头。front 读取队头，判空和长度操作维护结构状态；空队列出队必须按接口规则处理下溢。",
                "像排队办理业务，新来的人站到队尾，等待最久的人从队头先接受服务。",
                ["queue", "FIFO"],
                ["stack-queue-concept"],
                ["cs408-linear-list-definition-operations"],
            ),
            topic(
                "circular-queue-representation",
                "循环队列的数组表示",
                "concept",
                "循环队列如何复用数组末端之后的空闲槽位？",
                "front 与 rear 通过模运算在数组中回绕，避免顺序队列产生假溢出。",
                "容量为 m 的循环队列用 front 指示队头、rear 指示下一入队位置或队尾，具体语义必须统一。逻辑位置通过下标模 m 映射到物理槽位，入队更新 rear=(rear+1) mod m，出队更新 front=(front+1) mod m。",
                "像环形跑道，指针越过最后一个编号后回到零号位置继续使用空槽。",
                ["circular queue", "环形队列"],
                ["stack-queue-sequential"],
                ["cs408-queue-fifo"],
            ),
            topic(
                "circular-queue-state",
                "循环队列判空、判满与长度",
                "formula",
                "循环队列如何区分队空和队满并计算长度？",
                "可牺牲一个槽位、增加 size 计数或设置标志位来区分 front=rear 的两种状态。",
                "牺牲一个槽位的约定下，front=rear 表示空，(rear+1) mod m=front 表示满，队列长度为 (rear-front+m) mod m，最多存 m-1 个元素。使用 size 计数时可存 m 个元素，但所有操作必须同步维护 size。",
                "像环形停车场预留一个空位作为状态标记，看到入口与出口指针重合时才不会混淆全空和全满。",
                ["queue full empty", "循环队列长度"],
                ["stack-queue-sequential"],
                ["cs408-circular-queue-representation"],
            ),
            topic(
                "linked-queue",
                "链队列",
                "concept",
                "链队列如何用头尾指针实现常数时间入队和出队？",
                "front 指向队头哨兵或首结点，rear 指向尾结点，在尾部插入、头部删除。",
                "常见带头结点链队列中，front 指向头结点，rear 指向最后一个数据结点。入队把新结点接到 rear.next 并更新 rear；出队删除 front.next，若删除后为空还需令 rear=front，避免尾指针悬空。",
                "像一条带入口和出口标记的链式队伍，入口标记随新成员移动，出口从前端逐个放行。",
                ["linked queue", "链式队列"],
                ["stack-queue-linked"],
                ["cs408-queue-fifo", "cs408-singly-linked-list"],
            ),
            topic(
                "multidimensional-array-address",
                "多维数组的行优先与列优先地址",
                "formula",
                "怎样把多维数组下标映射为连续存储地址？",
                "行优先让最右下标变化最快，列优先让最左下标变化最快，地址由各维跨度加权求和。",
                "二维数组 A[m][n] 每元素占 L 字节、下标从 0 开始时，行优先地址为 base+(i·n+j)L，列优先为 base+(j·m+i)L。更高维数组按每一维之后或之前各维长度的乘积计算跨度，并先统一下标基准。",
                "像把表格逐行或逐列卷成一条纸带，下标必须先数完前面的整行或整列。",
                ["row major", "column major"],
                ["multidimensional-array-storage"],
                ["cs408-sequential-list-storage"],
            ),
            topic(
                "symmetric-matrix-compression",
                "对称矩阵压缩存储",
                "formula",
                "对称矩阵如何只保存一半元素并完成下标映射？",
                "因 aij=aji，只需按行或列保存上三角或下三角的 n(n+1)/2 个元素。",
                "n 阶对称矩阵可只保存含主对角线的一侧。按行存下三角且下标从 0 开始时，i≥j 的元素位置 k=i(i+1)/2+j；若 i<j，则先交换 i、j 再用同一公式。映射必须与存储三角和下标基准一致。",
                "像镜面对称图案只保存一侧，另一侧查询时先映射到镜像位置。",
                ["symmetric matrix", "下三角压缩"],
                ["special-matrix-compression"],
                ["cs408-multidimensional-array-address"],
            ),
            topic(
                "triangular-diagonal-matrix-compression",
                "三角矩阵与带状矩阵压缩",
                "formula",
                "三角矩阵和带状矩阵如何利用结构性零元素节省空间？",
                "三角矩阵保存一侧与公共常量，带状矩阵只保存主对角线附近固定宽度的非零带。",
                "上、下三角矩阵的一侧元素为同一常量，可将有效三角区域映射到连续数组并额外保存常量。三对角等带状矩阵只存满足 |i-j|≤d 的元素，按有效元素在各行中的累计个数推导一维下标；越界位置返回结构性零或常量。",
                "像只记录舞台聚光灯覆盖的斜带区域，其余固定黑暗位置无需逐个保存。",
                ["triangular matrix", "band matrix"],
                ["special-matrix-compression"],
                ["cs408-multidimensional-array-address"],
            ),
            topic(
                "sparse-matrix-triples",
                "稀疏矩阵三元组表示",
                "concept",
                "稀疏矩阵如何只记录非零元素？",
                "三元组表为每个非零元素保存行号、列号和值，并记录矩阵规模。",
                "当非零元素远少于总元素时，可用 (row,column,value) 三元组按行或列有序保存非零项，同时记录行数、列数和非零项数。访问任意位置不再是直接 O(1)，但存储量从 Θ(mn) 降为与非零项数量 t 同阶。",
                "像只在地图上登记有建筑的坐标和值，而不是为每块空地都建立记录。",
                ["sparse matrix", "triple table"],
                ["special-matrix-compression"],
                ["cs408-multidimensional-array-address"],
            ),
            topic(
                "queue-applications",
                "队列在层次处理与缓冲中的应用",
                "application",
                "队列为什么适合层次遍历、广度搜索和请求缓冲？",
                "FIFO 能保持发现顺序或到达顺序，使同一层任务先处理完再进入下一层。",
                "树的层次遍历和图的 BFS 将新发现结点入队，按发现先后出队；操作系统和网络缓冲也可按到达顺序排队。队列保证的是处理顺序，不自动保证公平、实时性或带权优先级。",
                "像候诊队列按到达顺序推进，也像逐层扩散的波纹先处理离起点近的层。",
                ["queue application", "buffer"],
                ["stack-queue-array-applications"],
                ["cs408-queue-fifo"],
            ),
        ],
    },
    {
        "id": "408-trees",
        "title": "Trees and Binary Trees",
        "title_zh": "树和二叉树",
        "guide_id": "cs408-syllabus-trees",
        "sections": [
            ("cs408-tree-basics", "Tree basics", "树的基本概念"),
            ("cs408-binary-tree", "Binary trees", "二叉树"),
            ("cs408-tree-forest", "Trees and forests", "树与森林"),
            ("cs408-tree-applications", "Applications", "树和二叉树应用"),
        ],
        "topics": [
            topic(
                "tree-terms",
                "树的结点、度、层次与路径",
                "concept",
                "树结构中的根、父子、度、层次、高度和路径分别是什么？",
                "树是由一个根和若干互不相交子树构成的层次结构，术语描述结点关系与整体形态。",
                "非空树有唯一根结点；除根外每个结点有唯一父结点。结点的子树数称为度，树的度是各结点度的最大值；叶结点度为 0。层次从根开始计数，高度是最大层次或最长向下路径长度，具体采用结点数还是边数必须说明。",
                "像组织架构图：最高负责人是根，每人只有一个直属上级但可有多个下属。",
                ["tree terminology", "node degree"],
                ["tree-concept"],
                ["cs408-logical-storage-operations"],
            ),
            topic(
                "tree-edge-node-properties",
                "树的结点数与边数性质",
                "theorem",
                "为什么含 n 个结点的非空树恰有 n-1 条边？",
                "除根外每个结点恰有一条来自父结点的边，因此边数等于非根结点数。",
                "非空树中根没有父边，其余 n-1 个结点各有且仅有一个父结点，对应一条入边，所以总边数为 n-1。各结点度数之和也等于边数；这些计数关系可用于由度分布求叶结点数。",
                "像公司中除最高负责人外每人只有一条直属汇报关系，汇报线数量就是员工数减一。",
                ["tree edge count", "度数之和"],
                ["tree-concept"],
                ["cs408-tree-terms"],
            ),
            topic(
                "binary-tree-properties",
                "二叉树定义与结点数性质",
                "theorem",
                "二叉树有哪些基本定义和计数性质？",
                "二叉树每个结点至多有左、右两个有序子树，第 i 层最多 2^(i-1) 个结点。",
                "二叉树的左右子树有顺序，不能随意交换。若根为第 1 层，第 i 层最多有 2^(i-1) 个结点，高度 h 的二叉树最多有 2^h-1 个结点；设度为 0、1、2 的结点数为 n0、n1、n2，则非空二叉树满足 n0=n2+1。",
                "像每个位置最多分成明确的左、右两个分支，因此层数增加时最多按两倍扩张。",
                ["binary tree", "n0=n2+1"],
                ["binary-tree-properties"],
                ["cs408-tree-terms"],
            ),
            topic(
                "full-complete-binary-tree",
                "满二叉树与完全二叉树",
                "comparison",
                "满二叉树和完全二叉树有什么区别？",
                "满二叉树每层都达到最大结点数，完全二叉树只要求按满树层序编号连续占据前 n 个位置。",
                "高度 h 的满二叉树含 2^h-1 个结点。完全二叉树除最后一层外均满，最后一层结点从左向右连续；按从 1 开始编号时，结点 i 的父结点为 floor(i/2)，孩子为 2i 与 2i+1（若存在）。",
                "满二叉树像每排座位全部坐满，完全二叉树允许最后一排从右侧开始空，但中间不能留洞。",
                ["full binary tree", "complete binary tree"],
                ["binary-tree-properties"],
                ["cs408-binary-tree-properties"],
            ),
            topic(
                "binary-tree-sequential-storage",
                "二叉树的顺序存储",
                "concept",
                "完全二叉树为什么适合用数组顺序存储？",
                "层序编号把父子关系转成简单下标公式，完全二叉树不会产生大量空槽。",
                "把根放在下标 1 时，结点 i 的左孩子、右孩子和父结点分别位于 2i、2i+1 和 floor(i/2)。该方法对完全二叉树空间紧凑；一般稀疏二叉树会因缺失结点保留大量空位置。",
                "像按楼层从左到右给座位编号，父子位置可以直接通过编号倍数计算。",
                ["array binary tree", "层序编号"],
                ["binary-tree-storage"],
                ["cs408-full-complete-binary-tree"],
            ),
            topic(
                "binary-tree-linked-storage",
                "二叉链表与三叉链表",
                "concept",
                "链式二叉树如何表示左右孩子和父结点？",
                "二叉链表结点保存数据、左孩子指针和右孩子指针，三叉链表再保存父指针。",
                "二叉链表适合一般形态的二叉树，空孩子用 null 表示；若二叉树有 n 个结点，2n 个孩子指针中有 n-1 个指向孩子，其余 n+1 个为空。增加 parent 指针形成三叉链表，可常数时间向上移动但增加空间与维护成本。",
                "像每个家谱卡片分别记录左、右后代，若再写上父代位置，就能同时向下和向上查找。",
                ["binary linked tree", "三叉链表"],
                ["binary-tree-storage"],
                ["cs408-binary-tree-properties"],
            ),
            topic(
                "binary-tree-depth-traversals",
                "二叉树先序、中序与后序遍历",
                "algorithm",
                "先序、中序和后序遍历如何安排根与左右子树的访问顺序？",
                "三种深度遍历分别采用根左右、左根右和左右根顺序，每个结点访问一次。",
                "先序遍历先访问根，再递归左、右子树；中序遍历先左子树，再根、右子树；后序遍历先左、右子树，最后访问根。递归实现时间 O(n)，额外栈空间与树高 h 同阶；非递归实现使用显式栈保存待处理状态。",
                "像处理文件夹时分别选择进入子目录前、左右目录之间或离开目录后记录当前文件夹。",
                ["preorder inorder postorder", "深度遍历"],
                ["binary-tree-traversal"],
                ["cs408-binary-tree-linked-storage", "cs408-stack-lifo"],
            ),
            topic(
                "binary-tree-level-order",
                "二叉树层序遍历",
                "algorithm",
                "层序遍历为什么需要队列？",
                "根先入队，每次出队访问结点并将其左右孩子入队，可按层从左到右访问。",
                "层序遍历用 FIFO 队列保存已发现但尚未访问的结点：根入队，循环取出队头并访问，再依次把非空左、右孩子入队。每个结点入队出队一次，时间 O(n)，队列最大空间取决于树的最大宽度。",
                "像按楼层参观大楼，先把当前层的房间全部登记，再进入下一层。",
                ["level order traversal", "层次遍历"],
                ["binary-tree-traversal"],
                ["cs408-binary-tree-linked-storage", "cs408-queue-fifo"],
            ),
            topic(
                "binary-tree-reconstruction",
                "由遍历序列重建二叉树",
                "algorithm",
                "哪些遍历序列组合能够唯一确定二叉树？",
                "结点互异时，先序加中序或中序加后序可唯一重建，一般仅有先序和后序不能唯一确定。",
                "先序的首元素或后序的末元素确定根，再用中序序列划分左右子树，递归处理各区间。若结点值重复，需要额外标识；层序加中序也可在一定条件下重建。递归切分时必须保持各序列子区间结点集合一致。",
                "像一份名单告诉谁先出现，另一份座次告诉左右分界，两份信息共同确定层次结构。",
                ["tree reconstruction", "遍历建树"],
                ["binary-tree-traversal"],
                ["cs408-binary-tree-depth-traversals"],
            ),
            topic(
                "threaded-binary-tree",
                "线索二叉树的线索化思想",
                "mechanism",
                "线索二叉树如何利用空孩子指针保存遍历前驱和后继？",
                "线索化用标志位区分孩子指针和线索，把部分空指针改为指向遍历前驱或后继。",
                "在二叉链表的 n+1 个空孩子指针中，可按某种遍历次序建立线索。ltag 或 rtag 标明对应指针是孩子还是线索；中序线索树最常见，能在不使用递归栈的情况下寻找中序前驱与后继。",
                "像把家谱卡片上原本空白的箭头改成“上一个访问者”和“下一个访问者”的快捷链接。",
                ["threaded binary tree", "线索化"],
                ["threaded-binary-tree"],
                ["cs408-binary-tree-linked-storage", "cs408-binary-tree-depth-traversals"],
            ),
            topic(
                "threaded-predecessor-successor",
                "中序线索树的前驱与后继",
                "algorithm",
                "怎样在中序线索树中寻找结点的直接前驱和后继？",
                "若对应标志为线索可直接返回；若为孩子，则沿子树寻找中序最右或最左结点。",
                "结点 p 的右指针若是后继线索，则 p.rchild 直接是中序后继；若指向右孩子，则后继是右子树中沿左孩子下降的最左结点。前驱对称：左线索可直接返回，否则在左子树中沿右孩子下降到最右结点。",
                "像快捷箭头存在时直接前往相邻访问者，否则进入对应分支寻找最靠边的结点。",
                ["inorder predecessor", "inorder successor"],
                ["threaded-binary-tree"],
                ["cs408-threaded-binary-tree"],
            ),
            topic(
                "tree-storage-representations",
                "树的双亲、孩子与孩子兄弟表示",
                "comparison",
                "一般树有哪些常见存储结构，各自适合什么操作？",
                "双亲表示便于向上查找，孩子链表便于枚举子女，孩子兄弟表示把多叉树转成二叉链式结构。",
                "双亲表示在结点数组中记录父下标；孩子表示为每个结点维护孩子链表；孩子兄弟表示让 firstChild 指向第一个孩子、nextSibling 指向下一个兄弟。不同表示的空间与查找方向不同，可组合父指针和孩子链表满足双向操作。",
                "像族谱可按“每人写父亲”“每人列孩子”或“只写长子和下一兄弟”三种方式登记。",
                ["parent representation", "child sibling"],
                ["tree-storage"],
                ["cs408-tree-terms"],
            ),
            topic(
                "tree-forest-binary-conversion",
                "树、森林与二叉树转换",
                "mechanism",
                "孩子兄弟表示如何在树、森林和二叉树之间转换？",
                "树的第一个孩子成为左孩子，下一个兄弟成为右孩子；森林各树根按兄弟关系连接。",
                "把一般树转换为二叉树时，结点的 firstChild 作为左孩子，nextSibling 作为右孩子。森林转换时先分别转换每棵树，再把各树根通过右孩子链相连。逆转换则把左孩子解释为第一个孩子、右链解释为兄弟。",
                "像把每个家庭的长子放在左侧，把同辈兄弟依次排在右侧，就能用二叉指针表达多叉关系。",
                ["forest conversion", "孩子兄弟法"],
                ["forest-conversion"],
                ["cs408-tree-storage-representations"],
            ),
            topic(
                "tree-forest-traversal",
                "树和森林的遍历",
                "algorithm",
                "树和森林的先根、后根遍历如何对应二叉树遍历？",
                "树的先根遍历对应孩子兄弟二叉树的先序，后根遍历对应其二叉树中序；森林按树的次序组合。",
                "树的先根遍历先访问根，再依次遍历各子树；后根遍历先依次遍历子树，最后访问根。森林的先序或中序遍历可借助孩子兄弟转换定义，必须保持各棵树及兄弟的原有次序。",
                "像参观多个园区：可先在入口登记再走子园区，也可走完所有子园区后再在入口登记。",
                ["preorder forest", "postorder tree"],
                ["tree-forest-traversal"],
                ["cs408-tree-forest-binary-conversion"],
            ),
            topic(
                "huffman-tree",
                "Huffman 树与带权路径长度",
                "algorithm",
                "Huffman 算法如何构造带权路径长度最小的二叉树？",
                "反复选取权值最小的两棵树合并，最终得到叶权给定时 WPL 最小的二叉树。",
                "带权路径长度 WPL 是各叶结点权值与其根到叶路径长度乘积之和。Huffman 构造每次从森林中取两棵根权最小的树作为新根的左右子树，新根权为两者之和，重复直到只剩一棵树。",
                "像总是先合并出现频率最低的两类任务，让高频任务尽量靠近根部以减少总成本。",
                ["Huffman tree", "WPL"],
                ["huffman"],
                ["cs408-tree-terms", "cs408-binary-heap"],
            ),
            topic(
                "huffman-coding",
                "Huffman 编码与前缀码",
                "application",
                "Huffman 树为什么能够生成无歧义的变长前缀编码？",
                "把字符放在叶结点并以左右边标 0/1，任一字符编码都不会成为另一编码的前缀。",
                "从根到字符叶结点的 0/1 路径形成编码。由于字符只对应叶结点，不存在某字符路径停在另一字符路径内部，因此编码具有前缀性质，可从左到右唯一解码。Huffman 编码在给定频率下最小化加权编码长度。",
                "像每个词都只写在决策树终点，读到终点才能完成一个词，所以不会在半路误判为另一个完整词。",
                ["Huffman code", "prefix code"],
                ["huffman"],
                ["cs408-huffman-tree"],
            ),
            topic(
                "disjoint-set",
                "并查集的集合表示与操作",
                "concept",
                "并查集如何维护互不相交集合的合并与代表元查询？",
                "每个集合用一棵父指针树表示，find 返回根代表元，union 连接两个不同根。",
                "并查集维护若干不相交集合。初始化时每个元素自成集合且 parent[x]=x；find(x) 沿父指针到根，union(x,y) 先找两根，若不同则把一棵根连接到另一棵。它适合动态连通性、Kruskal 判环和等价类合并。",
                "像每个小组成员沿负责人链找到组长，合并小组时只需让一个组长归到另一个组长名下。",
                ["disjoint set union", "DSU"],
                ["disjoint-set"],
                ["cs408-tree-terms"],
            ),
            topic(
                "disjoint-set-optimization",
                "并查集的路径压缩与按秩合并",
                "mechanism",
                "路径压缩和按秩合并怎样降低并查集树高？",
                "find 时把路径结点直接连到根，union 时让较浅或较小的树挂到较深或较大的树下。",
                "路径压缩在 find 返回时更新沿途 parent 为根；按秩或按大小合并避免把大树挂到小树下。两种优化组合后，m 次操作的摊还时间为 O(m·α(n))，其中 α 增长极慢，实践中接近常数。",
                "像查组织关系后把所有中间联系人直接记成总部，同时合并公司时让小团队并入大团队。",
                ["path compression", "union by rank"],
                ["disjoint-set"],
                ["cs408-disjoint-set"],
            ),
            topic(
                "binary-heap",
                "二叉堆的结构与堆序性",
                "concept",
                "二叉堆怎样同时满足完全二叉树结构和局部有序条件？",
                "二叉堆是完全二叉树，大根堆父关键字不小于孩子，小根堆父关键字不大于孩子。",
                "二叉堆通常用数组层序存储。大根堆保证每条父子边上父值≥子值，因此根为全局最大值；小根堆相反。堆只保证父子局部有序，兄弟和不同子树之间不要求完全排序。",
                "像锦标赛层级中每位上级至少不弱于直接下级，但不同分区的成员并没有完整名次。",
                ["binary heap", "heap order"],
                ["heap"],
                ["cs408-full-complete-binary-tree"],
            ),
            topic(
                "heap-operations",
                "堆的插入、删除与建堆",
                "algorithm",
                "上滤、下滤和自底向上建堆如何维护堆序？",
                "插入在末尾后上滤，删除根用末元素补位后下滤，自底向上建堆为 O(n)。",
                "插入保持完全树形状，在数组末尾加入元素并与父结点比较上滤，时间 O(log n)。删除堆顶后把末元素移到根并与更合适的孩子交换下滤，时间 O(log n)。从最后一个非叶结点起依次下滤可在线性时间建堆。",
                "像新选手从末级逐轮挑战上级，冠军离开后让末位临时补位并向下调整到合适层级。",
                ["sift up", "sift down"],
                ["heap"],
                ["cs408-binary-heap"],
            ),
            topic(
                "heap-applications",
                "堆与优先队列、Top-K",
                "application",
                "堆为什么适合实现优先队列和 Top-K？",
                "堆能 O(1) 查看极值、O(log n) 插入或删除极值，并只维护必要的局部顺序。",
                "优先队列用堆顶表示当前最高或最低优先级。求最大的 K 个元素时可维护容量 K 的小根堆：新元素超过堆顶才替换并下滤，总时间 O(n log K)、空间 O(K)。堆不适合快速查找任意指定元素。",
                "像只维护领奖台门槛，关心当前前 K 名及最低入围分，不必把所有人完整排序。",
                ["priority queue", "Top K"],
                ["heap"],
                ["cs408-heap-operations"],
            ),
        ],
    },
    {
        "id": "408-graphs",
        "title": "Graphs",
        "title_zh": "图",
        "guide_id": "cs408-syllabus-graphs",
        "sections": [
            ("cs408-graph-basics", "Graph basics", "图的基本概念"),
            ("cs408-graph-storage", "Storage", "图的存储与操作"),
            ("cs408-graph-traversal", "Traversal", "图的遍历"),
            ("cs408-graph-applications", "Applications", "图的应用"),
        ],
        "topics": [
            topic(
                "graph-definition",
                "图、顶点与边",
                "concept",
                "图结构如何表示元素之间的多对多关系？",
                "图 G=(V,E) 由顶点集合和边集合组成，边表示任意两个顶点之间的关系。",
                "图由非空有限顶点集合 V 和边集合 E 构成。无向边是无序顶点对，有向边或弧是有序对；不存在重复边且通常不含自环的图称简单图。图不要求像树那样每个结点只有一个父结点。",
                "像社交网络中用户是顶点，关注或好友关系是边，一个用户可以同时连接许多人。",
                ["graph", "vertex edge"],
                ["graph-concept"],
                ["cs408-logical-storage-operations"],
            ),
            topic(
                "graph-degree-path-connectivity",
                "图的度、路径与连通性",
                "concept",
                "图中的度、路径、回路、连通和强连通怎样定义？",
                "无向图的度是关联边数，有向图区分入度与出度；路径连接顶点，连通性描述能否互相到达。",
                "无向图所有顶点度数之和等于 2|E|；有向图入度总和与出度总和都等于 |E|。路径是相邻边组成的顶点序列，首尾相同可形成回路；无向图任意顶点互通称连通，有向图任意有序顶点对互达称强连通。",
                "像交通网中路口连接道路数量是度，能否沿道路到达决定连通，单行道路还要区分进入和离开方向。",
                ["degree connectivity", "strongly connected"],
                ["graph-concept"],
                ["cs408-graph-definition"],
            ),
            topic(
                "adjacency-matrix",
                "图的邻接矩阵",
                "concept",
                "邻接矩阵如何记录顶点对之间是否有边或边权？",
                "n 个顶点用 n×n 矩阵表示连接，查边 O(1)，空间始终 O(n²)。",
                "无权图中 A[i][j] 表示是否存在边，有权图可保存权值并用特殊值表示无边。无向图矩阵对称，顶点 i 的度可由第 i 行求和；邻接矩阵适合稠密图和频繁查边，但枚举邻居需要扫描一整行。",
                "像一张顶点对照表，每个行列交叉格直接回答两点是否相连。",
                ["adjacency matrix", "图矩阵"],
                ["graph-adjacency-matrix"],
                ["cs408-graph-definition"],
            ),
            topic(
                "adjacency-list",
                "图的邻接表",
                "concept",
                "邻接表如何只保存实际存在的边？",
                "每个顶点维护邻接顶点链表或动态表，空间为 O(V+E)，适合稀疏图。",
                "邻接表包含顶点表和每个顶点的边表。无向边通常在两个端点的表中各出现一次，有向边可保存出边或入边。枚举顶点邻居与其度数同阶，但判断任意两点是否相邻可能需要搜索边表。",
                "像每个人只保存自己的联系人清单，而不是维护所有用户两两组合的大表格。",
                ["adjacency list", "边表"],
                ["graph-adjacency-list"],
                ["cs408-graph-definition"],
            ),
            topic(
                "orthogonal-list",
                "有向图的十字链表",
                "concept",
                "十字链表如何同时组织有向图的入边和出边？",
                "每条弧结点同时挂在弧尾的出边链和弧头的入边链中。",
                "十字链表的顶点结点保存 firstIn 与 firstOut；弧结点保存 tail、head、沿同弧尾的下一出边和沿同弧头的下一入边。它能方便枚举一个顶点的所有入边或出边，并支持有向图边的动态修改。",
                "像一张转账记录同时归档在付款人的支出清单和收款人的收入清单中。",
                ["orthogonal list", "cross linked list"],
                ["graph-multilist-orthogonal"],
                ["cs408-graph-definition"],
            ),
            topic(
                "adjacency-multilist",
                "无向图的邻接多重表",
                "concept",
                "邻接多重表如何让一条无向边只保存一次？",
                "每条边结点记录两个端点，并分别链接到两个端点的关联边链。",
                "邻接多重表的边结点含两个端点编号，以及沿两个端点关联边链的下一指针。与普通邻接表把无向边复制两次不同，它让一条边只存在一个边结点，适合需要频繁标记、删除或访问边对象的无向图。",
                "像一份共同合同只保存一份原件，但同时出现在双方的合同索引中。",
                ["adjacency multilist", "无向边结点"],
                ["graph-multilist-orthogonal"],
                ["cs408-graph-definition"],
            ),
            topic(
                "graph-storage-comparison",
                "图存储结构与基本操作比较",
                "comparison",
                "怎样根据图的稠密度和操作类型选择存储结构？",
                "邻接矩阵适合稠密图和 O(1) 查边，邻接表适合稀疏图和枚举邻居，专用链表便于操作边对象。",
                "选择存储结构时应比较 O(V²) 与 O(V+E) 空间、查边、枚举邻居、计算度数、插删边和遍历成本。算法复杂度也依赖表示：例如邻接表 DFS/BFS 为 O(V+E)，邻接矩阵实现通常为 O(V²)。",
                "像选择地图：完整距离表查任意两点快，路线清单更节省稀疏路网的空间。",
                ["graph representation", "稠密图稀疏图"],
                ["graph-adjacency-matrix", "graph-adjacency-list", "graph-multilist-orthogonal"],
                ["cs408-adjacency-matrix", "cs408-adjacency-list"],
            ),
            topic(
                "depth-first-search",
                "深度优先搜索",
                "algorithm",
                "DFS 如何沿一条路径尽可能深入后再回溯？",
                "访问顶点后递归或用栈处理未访问邻接点，走不通时回退到最近分叉。",
                "DFS 为每个顶点维护 visited 标记。访问 u 后依次检查邻接点 v，未访问则递归 DFS(v)；非递归版本用显式栈。对非连通图需从每个未访问顶点重新启动，得到深度优先森林。",
                "像探索迷宫时沿一条岔路走到底，遇到死路再退回最近尚有未走分支的位置。",
                ["DFS", "depth first search"],
                ["graph-dfs"],
                ["cs408-adjacency-list", "cs408-stack-lifo"],
            ),
            topic(
                "breadth-first-search",
                "广度优先搜索",
                "algorithm",
                "BFS 如何按距起点的层次逐层访问图？",
                "起点入队，出队时把所有未访问邻接点标记并入队，从而按最少边数距离分层。",
                "BFS 在发现顶点时立即设置 visited 并入队，避免同一顶点被重复加入。无权图中，顶点第一次被发现时的层数就是从起点出发的最短边数；对非连通图需对未访问顶点重复启动。",
                "像水波从起点向外扩散，先覆盖一跳可达位置，再覆盖两跳位置。",
                ["BFS", "breadth first search"],
                ["graph-bfs"],
                ["cs408-adjacency-list", "cs408-queue-fifo"],
            ),
            topic(
                "graph-traversal-complexity",
                "图遍历复杂度与生成森林",
                "theorem",
                "DFS 与 BFS 的时间、空间和生成结构由什么决定？",
                "邻接表遍历为 O(V+E)，邻接矩阵为 O(V²)，搜索树边记录首次发现关系。",
                "DFS 与 BFS 都保证每个顶点至多正式访问一次。邻接表中每条边被检查常数次，时间 O(V+E)；邻接矩阵需扫描顶点行，时间 O(V²)。连通图的一次搜索产生生成树，非连通图产生生成森林；遍历序列还受邻接点存储次序影响。",
                "像巡检路网，清单地图只查看实际道路，矩阵地图则每到一处都要扫描所有潜在方向。",
                ["traversal complexity", "spanning forest"],
                ["graph-dfs", "graph-bfs"],
                ["cs408-depth-first-search", "cs408-breadth-first-search"],
            ),
            topic(
                "minimum-spanning-tree",
                "最小生成树问题",
                "concept",
                "最小生成树要求在什么图中优化什么目标？",
                "连通无向带权图的最小生成树连接全部顶点、无环且总边权最小。",
                "含 V 个顶点的生成树恰有 V-1 条边。最小生成树优化整棵连接结构的总权值，不保证任意两点在树上的路径都是原图最短路径；权值相同可能导致多个不同但同权的最小生成树。",
                "像用总成本最低的 V-1 条线路把所有站点连成无环网络，而不是分别优化每对站点距离。",
                ["MST", "minimum spanning tree"],
                ["minimum-spanning-tree"],
                ["cs408-graph-degree-path-connectivity"],
            ),
            topic(
                "prim-algorithm",
                "Prim 最小生成树算法",
                "algorithm",
                "Prim 算法如何逐步扩大一个连通顶点集合？",
                "每次选择连接已选集合与未选顶点的最小权边，把新顶点加入生成树。",
                "Prim 从任意起点开始，维护每个未选顶点到当前树的最小连接代价及前驱。每轮选代价最小顶点加入并更新其邻居。朴素邻接矩阵实现为 O(V²)，配合堆和邻接表可达 O(E log V)。",
                "像从一个岛开始，每次修建连接现有岛群与外部岛屿的最便宜桥梁。",
                ["Prim", "cut property"],
                ["minimum-spanning-tree"],
                ["cs408-minimum-spanning-tree"],
            ),
            topic(
                "kruskal-algorithm",
                "Kruskal 最小生成树算法",
                "algorithm",
                "Kruskal 算法如何按边权从小到大避免成环？",
                "排序所有边，依次加入连接两个不同连通分量的最小边，直到选出 V-1 条。",
                "Kruskal 将边按非降权排序，使用并查集判断端点是否已在同一分量；不同则选边并 union，相同则跳过以避免环。主要成本来自排序，常为 O(E log E)，适合边集和稀疏图。",
                "像从最便宜线路开始采购，但任何会在现有网络中形成闭环的线路都不再购买。",
                ["Kruskal", "edge sorting"],
                ["minimum-spanning-tree"],
                ["cs408-minimum-spanning-tree", "cs408-disjoint-set"],
            ),
            topic(
                "shortest-path-problem",
                "最短路径问题与松弛",
                "concept",
                "最短路径问题如何区分单源和全源，并用松弛改进距离？",
                "最短路径最小化路径边权之和，松弛用经过中间顶点的新路径尝试降低当前估计。",
                "单源最短路径求一个源点到其余顶点的距离，全源最短路径求所有有序顶点对。对边 (u,v,w) 的松弛检查 dist[v]>dist[u]+w，成立则更新距离和前驱；算法是否正确取决于边权条件和处理顺序。",
                "像不断检查经某个中转站是否能得到更便宜路线，并更新路线表和上一站。",
                ["shortest path", "relaxation"],
                ["shortest-path"],
                ["cs408-graph-degree-path-connectivity"],
            ),
            topic(
                "dijkstra-algorithm",
                "Dijkstra 单源最短路径",
                "algorithm",
                "Dijkstra 为什么只适用于非负权图？",
                "每轮永久确定当前距离最小的未确定顶点，再松弛其出边；非负权保证该距离不会被以后路径降低。",
                "初始化源距离为 0、其余为无穷。反复选择最小暂定距离顶点 u 加入已确定集合并松弛 u 的出边。朴素实现 O(V²)，堆优化常为 O((V+E)log V)。存在负权边时，已确定顶点仍可能被后来路径改进，贪心依据失效。",
                "像在所有未确认路线中先确认当前最便宜的站点，只有后续道路费用不为负时这个确认才安全。",
                ["Dijkstra", "nonnegative weights"],
                ["shortest-path"],
                ["cs408-shortest-path-problem", "cs408-binary-heap"],
            ),
            topic(
                "floyd-warshall",
                "Floyd 全源最短路径",
                "algorithm",
                "Floyd 算法如何逐步允许更多中间顶点？",
                "动态规划按中间顶点 k 更新 dist[i][j]=min(dist[i][j],dist[i][k]+dist[k][j])。",
                "初始距离矩阵保存直接边权、对角线为 0。第 k 轮后，dist[i][j] 表示中间顶点只允许来自前 k 个顶点的最短距离。三重循环时间 O(V³)、空间 O(V²)，可处理负边但不能存在可达负环。",
                "像逐个开放中转城市，每开放一个城市就检查所有起终点是否能经它得到更短路线。",
                ["Floyd Warshall", "all pairs shortest path"],
                ["shortest-path"],
                ["cs408-shortest-path-problem", "cs408-adjacency-matrix"],
            ),
            topic(
                "topological-sort",
                "拓扑排序与有向无环图",
                "algorithm",
                "怎样生成满足所有先后依赖的拓扑序并检测有向环？",
                "反复输出入度为 0 的顶点并删除其出边；若未输出全部顶点则图中存在有向环。",
                "拓扑序要求每条弧 u→v 中 u 都出现在 v 之前。Kahn 算法维护入度和零入度队列，时间 O(V+E)；某一步有多个零入度顶点意味着拓扑序可能不唯一。只有 DAG 才存在拓扑序。",
                "像安排先修课程：只有所有先修要求已完成的课程才能进入下一位置。",
                ["topological sort", "DAG"],
                ["topological-sort"],
                ["cs408-adjacency-list", "cs408-queue-fifo"],
            ),
            topic(
                "critical-path",
                "AOE 网与关键路径",
                "algorithm",
                "关键路径如何确定工程最短工期和不能延误的活动？",
                "在 AOE 网中计算事件最早、最迟发生时间，时间余量为 0 的活动组成关键路径。",
                "AOE 网以顶点表示事件、带权有向边表示活动和持续时间。按拓扑序前推求 ve，逆拓扑序后推求 vl；活动 a=<u,v> 的最早开始 e=ve[u]，最迟开始 l=vl[v]-weight(a)，l-e=0 时为关键活动。延误关键活动通常会延误工期。",
                "像项目计划表中没有任何机动时间的任务链，任一任务延迟都会直接推迟最终交付。",
                ["critical path", "AOE network"],
                ["critical-path"],
                ["cs408-topological-sort"],
            ),
        ],
    },
    {
        "id": "408-searching",
        "title": "Searching",
        "title_zh": "查找",
        "guide_id": "cs408-syllabus-searching",
        "sections": [
            ("cs408-search-basics", "Search basics", "查找基本概念"),
            ("cs408-linear-search", "Linear and indexed search", "线性与索引查找"),
            ("cs408-tree-search", "Tree search", "树型查找"),
            ("cs408-hash-search", "Hashing", "散列查找"),
            ("cs408-string-search", "String matching", "字符串模式匹配"),
        ],
        "topics": [
            topic(
                "search-concepts",
                "查找表、关键字与查找结果",
                "concept",
                "查找问题中的查找表、关键字、成功与失败分别是什么？",
                "查找依据关键字在记录集合中确定匹配记录，成功返回位置或记录，失败确认不存在。",
                "查找表是同一类型记录构成的集合，关键字是能标识或区分记录的数据项。静态查找表只查询，动态查找表还允许插入和删除；评价算法时必须同时考虑成功、失败查找以及数据是否有序。",
                "像在档案库中按身份证号或姓名寻找记录，既要处理找到，也要能确定确实不存在。",
                ["search table", "key"],
                ["search-concept"],
                ["cs408-abstract-data-type"],
            ),
            topic(
                "average-search-length",
                "平均查找长度",
                "formula",
                "平均查找长度如何衡量一次查找的期望比较次数？",
                "ASL 是各查找情况比较次数按发生概率加权的期望，成功与失败通常分别计算。",
                "若第 i 种查找情况发生概率为 pi、需要 ci 次关键字比较，则 ASL=Σpi·ci。概率未知时常假设等概率。不同算法的失败查找可能对应区间、空链或探测终点，必须按具体结构列出失败情况。",
                "像统计平均排队时间，不只看最长队伍，还要按各队伍出现概率加权。",
                ["ASL", "average search length"],
                ["search-concept", "search-analysis-applications"],
                ["cs408-search-concepts"],
            ),
            topic(
                "sequential-search",
                "顺序查找",
                "algorithm",
                "顺序查找怎样在线性表中寻找目标关键字？",
                "从一端逐个比较直到找到或扫描结束，适用于无序表和链式存储，时间为 O(n)。",
                "顺序查找不要求记录有序。成功比较次数取决于目标位置，失败需要检查所有 n 个记录；等概率时成功 ASL 约为 (n+1)/2，失败为 n 或 n+1，取决于计数和哨兵约定。",
                "像从名册第一页逐行核对姓名，找到就停，否则必须看到最后。",
                ["linear search", "sequential search"],
                ["sequential-search"],
                ["cs408-search-concepts"],
            ),
            topic(
                "sequential-search-sentinel",
                "带哨兵的顺序查找",
                "mechanism",
                "哨兵如何减少顺序查找循环中的边界判断？",
                "把目标暂存到数组边界位置，循环只比较关键字，停下后再判断是否命中有效记录。",
                "常见从后向前查找把待查关键字写入下标 0 作为哨兵，从 n 开始递减直到相等；返回 0 表示失败。哨兵不改变 O(n) 复杂度，只减少循环内的边界分支，且必须确保额外槽位可写。",
                "像在走廊尽头放一块同名终点牌，保证搜索总会停下，再判断停在真实房间还是终点牌。",
                ["sentinel search", "哨兵"],
                ["sequential-search"],
                ["cs408-sequential-search"],
            ),
            topic(
                "block-search",
                "分块查找",
                "algorithm",
                "分块查找如何用块间有序与块内无序折中查找成本？",
                "索引表记录每块最大关键字和起始位置，先定位块再在块内顺序查找。",
                "分块查找要求各块之间满足前一块最大关键字小于后一块最小关键字，但块内可无序。先对有序索引顺序或折半查找，再扫描候选块；块大小影响索引查找和块内扫描的平衡。",
                "像图书先按大区间分架，先找到目标书架，再在架内逐本查找。",
                ["indexed sequential search", "分块索引"],
                ["block-search"],
                ["cs408-sequential-search"],
            ),
            topic(
                "binary-search",
                "折半查找",
                "algorithm",
                "折半查找怎样利用有序顺序表不断缩小区间？",
                "比较中点后排除不可能的一半，成功和失败时间均为 O(log n)。",
                "折半查找要求支持随机访问且关键字有序。维护闭区间 [low,high] 或半开区间，按统一约定计算 mid；目标小于中值缩小右界，大于则提高左界。循环条件和边界更新必须保证区间严格缩小。",
                "像在有序字典中先翻中间页，根据字母顺序只保留前半或后半继续查。",
                ["binary search", "二分查找"],
                ["binary-search"],
                ["cs408-search-concepts", "cs408-sequential-list-storage"],
            ),
            topic(
                "binary-search-decision-tree",
                "折半查找判定树与 ASL",
                "theorem",
                "折半查找的比较过程如何对应判定树？",
                "每次中点比较对应一层判定，成功结点深度和失败外部结点深度决定比较次数。",
                "对固定长度有序表，折半查找的比较过程可画成近似平衡的二叉判定树。成功查找某元素的比较次数等于其结点层数；失败对应叶间空区间。树高为 floor(log2 n)+1，因此最坏比较次数为 O(log n)。",
                "像一棵问答决策树，每回答一次“大于还是小于”就走向一侧，路径长度就是比较次数。",
                ["binary search tree of decisions", "判定树"],
                ["binary-search", "search-analysis-applications"],
                ["cs408-binary-search", "cs408-average-search-length"],
            ),
            topic(
                "bst-property-search",
                "二叉搜索树性质与查找",
                "concept",
                "二叉搜索树怎样利用关键字有序性查找？",
                "对每个结点，左子树关键字更小、右子树更大，中序遍历得到有序序列。",
                "查找从根开始，目标小于当前关键字进入左子树，大于则进入右子树，相等成功。时间与树高 h 同阶；形态平衡时约 O(log n)，按有序序列插入可能退化为链，最坏 O(n)。",
                "像在层级目录中，每次根据目标偏小或偏大只进入一侧分支。",
                ["BST", "binary search tree"],
                ["binary-search-tree"],
                ["cs408-binary-tree-linked-storage", "cs408-search-concepts"],
            ),
            topic(
                "bst-insert-delete",
                "二叉搜索树插入与删除",
                "algorithm",
                "BST 怎样插入新关键字并删除不同度数的结点？",
                "插入落在失败查找位置；删除叶或单孩子结点直接接替，双孩子结点用前驱或后继替换。",
                "插入沿查找路径到空指针建立叶结点。删除叶结点直接断开；只有一个孩子时让孩子接替；有两个孩子时用中序前驱或后继的关键字替换目标，再删除那个至多只有一个孩子的结点。所有修改必须保持中序有序。",
                "像维护分类目录：新记录放到唯一空位，删除中间目录时用相邻有序记录接班。",
                ["BST insertion", "BST deletion"],
                ["binary-search-tree"],
                ["cs408-bst-property-search"],
            ),
            topic(
                "avl-balance",
                "AVL 树的平衡条件与高度",
                "theorem",
                "AVL 树如何用平衡因子限制树高？",
                "每个结点左右子树高度差绝对值不超过 1，因此查找、插入和删除保持 O(log n)。",
                "AVL 树是二叉搜索树，结点平衡因子通常定义为左子树高度减右子树高度，合法值为 -1、0、1。插入或删除可能使祖先失衡，需要旋转恢复；最少结点数满足类似 Fibonacci 的递推，因此高度为 O(log n)。",
                "像一架层层保持近似水平的天平，任何位置两侧高度都不能相差超过一层。",
                ["AVL tree", "balance factor"],
                ["avl-tree"],
                ["cs408-bst-property-search"],
            ),
            topic(
                "avl-rotations",
                "AVL 的 LL、RR、LR、RL 旋转",
                "algorithm",
                "四类 AVL 失衡分别怎样通过旋转恢复？",
                "外侧失衡做一次单旋，内侧失衡先对子树再对失衡结点做双旋。",
                "LL 型对失衡结点右旋，RR 型左旋；LR 型先对左孩子左旋再对失衡结点右旋，RL 型相反。旋转只改变局部父子关系，必须同步更新高度，同时保持中序序列不变。",
                "像调整弯折的支架：外侧单弯一次扶正，内侧折线先把下层方向转正再扶正上层。",
                ["AVL rotation", "LL LR RR RL"],
                ["avl-tree"],
                ["cs408-avl-balance"],
            ),
            topic(
                "avl-updates",
                "AVL 插入与删除后的调整",
                "mechanism",
                "AVL 更新后为什么要沿搜索路径向上检查平衡？",
                "插入或删除只会改变搜索路径上的子树高度，沿祖先方向更新并在首个或多个失衡点旋转。",
                "插入新叶后自底向上更新高度，通常修复第一个失衡点即可恢复更高祖先高度；删除可能让子树高度继续下降，因此可能需要一路修复多个祖先。旋转类型由失衡结点和较高孩子、孙子的方向确定。",
                "像修改建筑最底层后逐层复核承重，插入常在首个问题处恢复，拆除可能让更高层继续变化。",
                ["AVL insertion deletion", "rebalance"],
                ["avl-tree"],
                ["cs408-avl-rotations"],
            ),
            topic(
                "red-black-properties",
                "红黑树的五条性质与黑高",
                "theorem",
                "红黑树通过哪些颜色约束保持近似平衡？",
                "根和空叶为黑，红结点孩子为黑，任一路径黑结点数相同，使高度不超过约 2log(n+1)。",
                "红黑树是带颜色的 BST：结点红或黑；根黑；所有空叶哨兵黑；红结点不能有红孩子；从任一结点到后代空叶的路径具有相同黑高。颜色约束允许比 AVL 更松的平衡，但保证基本操作 O(log n)。",
                "像交通网络允许局部红色快速路，但不能连续出现，且每条到出口的黑色检查站数量一致。",
                ["red black tree", "black height"],
                ["red-black-tree"],
                ["cs408-bst-property-search"],
            ),
            topic(
                "red-black-adjustment",
                "红黑树插入与删除调整",
                "mechanism",
                "红黑树更新后怎样用变色和旋转恢复性质？",
                "插入主要修复红红冲突，删除主要修复黑高亏损，通过观察父、叔、兄弟颜色选择变色或旋转。",
                "新插入结点通常染红以不改变黑高；若父也红，则根据叔结点颜色进行向上变色或旋转。删除黑结点可能造成双黑语义，按兄弟及其孩子颜色分类调整。考试重点是性质、局部情形与结果不变量，而非死记代码行。",
                "像维护各路线检查站配额，新增先用不计配额的红站，冲突时再重新着色或调整局部路线。",
                ["red black insertion", "red black deletion"],
                ["red-black-tree"],
                ["cs408-red-black-properties", "cs408-bst-insert-delete"],
            ),
            topic(
                "b-tree-properties",
                "B 树的阶、关键字数与平衡",
                "concept",
                "m 阶 B 树如何限制结点分支和关键字数量？",
                "B 树是所有叶结点同层的多路平衡搜索树，每结点保存有序关键字和多个孩子。",
                "m 阶 B 树中每个结点至多 m 个孩子和 m-1 个关键字；除根外非叶结点至少有 ceil(m/2) 个孩子，根若非叶至少两个孩子。含 k 个关键字的内部结点有 k+1 个孩子，关键字把孩子子树的取值范围分隔开。",
                "像一页目录同时保存多个分隔词和多个下级页码，让树更矮以减少外存访问。",
                ["B-tree", "m-way search tree"],
                ["b-tree-b-plus-tree"],
                ["cs408-search-concepts"],
            ),
            topic(
                "b-tree-search",
                "B 树查找",
                "algorithm",
                "B 树查找怎样在结点内比较并选择下一孩子？",
                "先在结点有序关键字中定位区间，命中则成功，否则沿对应孩子继续，直到叶层。",
                "每访问一个 B 树结点，先在其关键字数组中顺序或折半查找。若目标等于某关键字返回；否则根据落入的关键字区间选择一个孩子。树高决定外存块访问次数，结点内部比较通常在内存完成。",
                "像先翻目录页找到目标词所在区间，再跳到对应子目录页。",
                ["B-tree search", "多路查找"],
                ["b-tree-b-plus-tree"],
                ["cs408-b-tree-properties"],
            ),
            topic(
                "b-tree-insertion",
                "B 树插入与分裂",
                "algorithm",
                "B 树插入溢出时怎样分裂结点并向上提升关键字？",
                "关键字插入叶结点，超过容量时以中间关键字为界分裂并把中间关键字提升到父结点。",
                "沿查找路径到叶层插入并保持有序。若关键字数超过 m-1，选择中间关键字上移，左右关键字和孩子分成两个结点；父结点也可能溢出并继续向上分裂，根分裂时新建根使树高增加 1。",
                "像目录页写满后分成前后两页，并把中间分隔词登记到上一层目录。",
                ["B-tree split", "B-tree insertion"],
                ["b-tree-b-plus-tree"],
                ["cs408-b-tree-search"],
            ),
            topic(
                "b-tree-deletion",
                "B 树删除、借位与合并",
                "algorithm",
                "B 树删除导致关键字不足时怎样恢复下界？",
                "先把内部关键字转换为叶层删除；下溢时向富余兄弟借关键字或与兄弟及父分隔字合并。",
                "删除内部关键字可用前驱或后继替换后转为叶删除。若非根结点低于最少关键字数，优先通过父分隔关键字与相邻富余兄弟旋转借位；无法借位时与兄弟及父分隔关键字合并，可能向上继续修复。根为空时由唯一孩子成为新根。",
                "像目录页内容太少时先向相邻页借条目，借不到就连同上层分隔词一起合并页面。",
                ["B-tree merge", "B-tree deletion"],
                ["b-tree-b-plus-tree"],
                ["cs408-b-tree-properties"],
            ),
            topic(
                "b-plus-tree",
                "B+ 树的索引与叶链",
                "concept",
                "B+ 树为什么把完整记录或关键字集中在叶结点？",
                "内部结点只作索引，全部查找最终到叶层，叶结点按关键字有序链接以支持范围扫描。",
                "B+ 树内部关键字用于分隔子树，真正的数据条目集中在叶结点；所有叶结点处于同层并通过链指针相连。内部结点能容纳更多索引项，树高较低，单点查找路径长度稳定，范围查询可沿叶链顺序扫描。",
                "像多级书目只保存导航词，完整书目卡片集中在最底层并按顺序串联。",
                ["B+ tree", "leaf linked list"],
                ["b-tree-b-plus-tree"],
                ["cs408-b-tree-properties"],
            ),
            topic(
                "b-tree-vs-b-plus",
                "B 树与 B+ 树比较",
                "comparison",
                "B 树和 B+ 树在数据位置、查找终点与范围访问上有什么区别？",
                "B 树内部结点可存数据并提前命中，B+ 树数据只在叶层且叶链更适合范围访问。",
                "B 树每个关键字只出现于某个结点，查找可能在内部层结束；B+ 树内部索引关键字可重复，所有成功查找都到叶层。B+ 树内部扇出通常更大、叶链支持顺序与范围查询，因此数据库和文件系统常采用 B+ 树变体。",
                "像一套目录把正文分散在各层，另一套所有正文都放在底层连续书架，上层只负责导航。",
                ["B-tree vs B+ tree", "多路树比较"],
                ["b-tree-b-plus-tree", "search-analysis-applications"],
                ["cs408-b-tree-properties", "cs408-b-plus-tree"],
            ),
            topic(
                "hash-table",
                "散列表与直接地址思想",
                "concept",
                "散列表如何由关键字直接计算存储位置？",
                "散列函数把关键字映射到表地址，目标是让查找不再依赖元素间比较顺序。",
                "散列表由散列函数 H(key) 和冲突处理策略组成。不同关键字可能映射到同一地址形成冲突；理想情况下，查找先计算地址，再在少量冲突记录中确认关键字，平均接近 O(1)，最坏仍可 O(n)。",
                "像根据邮政编码直接找到分拣格口，但不同地址可能进入同一格，需要额外区分。",
                ["hash table", "哈希表"],
                ["hash-table"],
                ["cs408-search-concepts"],
            ),
            topic(
                "hash-functions",
                "散列函数设计",
                "mechanism",
                "怎样设计能均匀分布关键字的散列函数？",
                "函数应计算快速、地址范围合法并尽量利用关键字信息，常用除留余数、直接定址、数字分析等方法。",
                "除留余数法 H(key)=key mod p 常选不大于表长的合适质数；直接定址适合关键字范围紧凑；数字分析、平方取中和折叠法按关键字分布选取信息。函数不能消除所有冲突，评价需结合实际关键字分布。",
                "像设计分拣规则，既要快速，又要避免大量包裹集中到少数格口。",
                ["hash function", "division method"],
                ["hash-table"],
                ["cs408-hash-table"],
            ),
            topic(
                "separate-chaining",
                "链地址法处理散列冲突",
                "algorithm",
                "链地址法如何保存映射到同一散列地址的多个记录？",
                "每个表槽保存一个桶或链表，冲突记录进入同一桶，删除不会破坏其他地址的查找路径。",
                "查找先计算 H(key)，再遍历对应桶。若桶内使用无序链表，期望成本取决于装填因子 α=n/m；表可容纳超过 m 个记录。链地址法需要指针或桶开销，但删除直接从桶中移除即可。",
                "像同一分拣格口挂一串标签，所有落入该格的包裹沿标签链继续区分。",
                ["separate chaining", "拉链法"],
                ["hash-table"],
                ["cs408-hash-functions", "cs408-singly-linked-list"],
            ),
            topic(
                "open-addressing",
                "开放定址法与探测序列",
                "algorithm",
                "开放定址法如何在表内寻找冲突后的空槽？",
                "按线性、平方或双散列探测序列检查其他槽，查找必须沿同一序列直到命中或遇到真正空槽。",
                "开放定址把所有记录保存在表数组内，要求装填因子小于 1。线性探测易产生一次聚集，平方探测和双散列改善分布；删除通常使用墓碑标记，直接置空会截断其他记录的探测链。",
                "像停车位被占后按固定规则继续找下一个候选车位，离场时要留标记避免误判后面没有车。",
                ["open addressing", "linear probing"],
                ["hash-table"],
                ["cs408-hash-functions"],
            ),
            topic(
                "hash-load-factor-asl",
                "散列表装填因子与查找性能",
                "theorem",
                "装填因子怎样影响散列冲突和平均查找长度？",
                "装填因子 α=n/m 越大通常冲突越多；性能还取决于散列函数、冲突策略和关键字分布。",
                "链地址法的平均桶长与 α 同阶，开放定址在 α 接近 1 时探测长度会急剧增加，因此需要扩容和重散列。计算 ASL 时应按实际插入产生的探测序列分别统计成功记录和各失败起始地址。",
                "像停车场越接近满位，寻找空位的平均绕行距离越长。",
                ["load factor", "hash ASL"],
                ["hash-table", "search-analysis-applications"],
                ["cs408-average-search-length", "cs408-open-addressing"],
            ),
            topic(
                "brute-force-string-matching",
                "朴素字符串模式匹配",
                "algorithm",
                "BF 模式匹配怎样逐个尝试文本起点？",
                "在每个可能起点从模式首字符开始比较，失配后文本起点右移一位重新开始。",
                "文本长度 n、模式长度 m 时，BF 最坏可能在许多起点重复比较相同字符，时间 O(nm)，额外空间 O(1)。若匹配成功返回起始位置；实现必须处理空模式和 n<m 等边界约定。",
                "像把透明模板依次覆盖到文本每个起点，每次都从模板第一格重新核对。",
                ["brute force matching", "BF 算法"],
                ["string-pattern-matching"],
                ["cs408-search-concepts"],
            ),
            topic(
                "kmp-prefix-function",
                "KMP 的最长相等前后缀",
                "mechanism",
                "KMP 如何用模式串自身的前后缀信息避免文本回退？",
                "前缀函数记录每个模式前缀的最长真前缀与真后缀长度，失配时模式跳到可复用边界。",
                "对模式 P[0..i]，π[i] 是其最长相等真前缀和真后缀长度。构造时若 P[i] 与当前边界字符失配，就令 j=π[j-1] 继续尝试；相等则 j 增一。所有回退总次数线性，因此构造时间 O(m)。",
                "像对齐失败时保留已经匹配尾部中同时也是开头的那一段，不必把文本指针退回。",
                ["prefix function", "failure function"],
                ["string-pattern-matching"],
                ["cs408-brute-force-string-matching"],
            ),
            topic(
                "kmp-matching",
                "KMP 模式匹配",
                "algorithm",
                "KMP 怎样在线性时间内完成文本与模式匹配？",
                "文本指针单调前进，模式失配时按前缀函数回退，整体时间 O(n+m)。",
                "扫描文本字符时维护已匹配模式长度 j；失配且 j>0 时令 j=π[j-1]，相等则 j++，j=m 时报告匹配起点并按需继续。模式回退不会让文本重新比较已扫描位置，预处理和匹配总时间为 O(m+n)。",
                "像尺子沿文本只向前移动，对齐失败时只在尺子内部调整起点。",
                ["KMP", "Knuth Morris Pratt"],
                ["string-pattern-matching"],
                ["cs408-kmp-prefix-function"],
            ),
            topic(
                "next-nextval",
                "KMP 的 next 与 nextval 数组",
                "formula",
                "不同教材中的 next、前缀函数和 nextval 为什么下标值可能不同？",
                "它们都编码失配后的模式跳转，但起始下标、长度语义和是否跳过重复字符的约定不同。",
                "有的教材用 next[j] 表示模式下标 j 失配后的新下标，并令 next[0]=-1；前缀函数 π 则保存长度并从 0 开始。nextval 在回退位置字符与当前字符相同时继续回退，避免立即重复比较。做题前必须先确认题目定义再计算。",
                "像不同导航系统都给出回退地点，但一个用站点编号、一个用已走长度，数字不能直接混用。",
                ["next array", "nextval"],
                ["string-pattern-matching", "search-analysis-applications"],
                ["cs408-kmp-prefix-function"],
            ),
            topic(
                "search-method-selection",
                "查找方法的分析与选择",
                "comparison",
                "怎样根据有序性、动态更新、存储介质和查询类型选择查找结构？",
                "选择应综合比较查找、插删、空间、顺序访问、范围查询和最坏情况保证。",
                "小型无序数据可顺序查找；静态有序顺序表适合二分；动态有序集合可用平衡树；外存索引适合 B/B+ 树；精确键查询可用散列表；前缀或模式查询需专门字符串算法。不能只比较平均查找时间而忽略更新和失败边界。",
                "像选择索引工具：纸质小清单、字典目录、文件柜索引和邮编分拣各适合不同任务。",
                ["search selection", "查找算法比较"],
                ["search-analysis-applications"],
                ["cs408-average-search-length", "cs408-b-tree-vs-b-plus", "cs408-hash-load-factor-asl"],
            ),
        ],
    },
    {
        "id": "408-sorting",
        "title": "Sorting",
        "title_zh": "排序",
        "guide_id": "cs408-syllabus-sorting",
        "sections": [
            ("cs408-sorting-basics", "Sorting foundations", "排序基础"),
            ("cs408-internal-sorting", "Internal sorting", "内部排序"),
            ("cs408-external-sorting", "External sorting", "外部排序"),
            ("cs408-sorting-analysis", "Analysis and selection", "排序分析与选择"),
        ],
        "topics": [
            topic(
                "sorting-concepts",
                "排序、稳定性与内部外部排序",
                "concept",
                "排序问题有哪些基本术语和评价维度？",
                "排序按关键字重排记录；稳定性描述相等关键字的相对次序，内部与外部排序按数据能否全部驻留内存区分。",
                "排序把记录序列按一个或多个关键字组织成非递减或非递增次序。若任意相等关键字记录在排序后仍保持原相对次序，算法稳定；否则不稳定。全部数据可在内存中完成的是内部排序，需要在内存与外存间分批交换数据的是外部排序。",
                "像按成绩整理报名表：同分学生是否保留原报名顺序体现稳定性，桌面放不下全部表格时就必须分批整理。",
                ["sorting stability", "internal sorting"],
                ["sorting-concept"],
            ),
            topic(
                "direct-insertion-sort",
                "直接插入排序",
                "algorithm",
                "直接插入排序怎样维护逐步扩大的有序区？",
                "每轮取出一个待排记录，在前方已排序区中从后向前寻找位置并移动记录后插入。",
                "第 i 轮把 A[i] 暂存为哨兵，从有序区 A[0..i-1] 末端向前比较；大于待插入关键字的记录依次后移，最终把暂存记录放入空位。最好时间 O(n)，平均和最坏 O(n²)，辅助空间 O(1)，通常稳定且适合基本有序或规模较小的数据。",
                "像整理手中扑克牌，每摸一张就从已排好的牌尾向前找到它的位置。",
                ["insertion sort", "straight insertion"],
                ["direct-insertion-sort", "sorting-analysis-applications"],
                ["cs408-sorting-concepts"],
            ),
            topic(
                "binary-insertion-sort",
                "折半插入排序",
                "algorithm",
                "折半插入排序减少了什么，又没有减少什么？",
                "它在有序区用二分查找定位插入点，减少关键字比较，但记录移动仍可能是二次量级。",
                "折半插入排序利用已排序前缀，在其中二分确定待排记录的插入位置，再整体后移其后的记录。比较次数降为 O(n log n)，但最坏和平均移动次数仍为 O(n²)，所以总时间仍是 O(n²)；用恰当的相等元素插入边界可保持稳定。",
                "像先用目录快速找到文件夹位置，但仍要把后面的全部文件挪开一格。",
                ["binary insertion sort", "折半插入"],
                ["binary-insertion-sort", "sorting-analysis-applications"],
                ["cs408-direct-insertion-sort", "cs408-binary-search"],
            ),
            topic(
                "bubble-sort",
                "冒泡排序",
                "algorithm",
                "冒泡排序如何通过相邻交换把极值送到边界？",
                "每趟比较相邻逆序对并交换，使当前未排序区的一个极值移动到最终位置。",
                "按升序的一种实现从前向后比较相邻记录，发现逆序就交换，于是一趟后最大元素到达末端；也可反向扫描把最小元素送到前端。若一趟没有交换可提前结束。最好 O(n)，平均和最坏 O(n²)，辅助空间 O(1)，只交换严格逆序对时稳定。",
                "像气泡在相邻位置间逐步上浮，一趟只能保证一个边界元素就位。",
                ["bubble sort", "起泡排序"],
                ["bubble-sort", "sorting-analysis-applications"],
                ["cs408-sorting-concepts"],
            ),
            topic(
                "selection-sort",
                "简单选择排序",
                "algorithm",
                "简单选择排序每趟怎样确定一个最终位置？",
                "每轮在未排序区选出最小记录，与该区首位置交换。",
                "第 i 轮扫描 A[i..n-1] 找到最小关键字下标，再与 A[i] 交换。无论初始次序如何，比较次数都是 n(n-1)/2，时间 O(n²)，交换次数 O(n)，辅助空间 O(1)。交换可能跨越相等记录，因此通常不稳定。",
                "像每次从剩余人群中找出最矮者，让他与队首直接换位。",
                ["selection sort", "simple selection"],
                ["selection-sort", "sorting-analysis-applications"],
                ["cs408-sorting-concepts"],
            ),
            topic(
                "shell-sort",
                "希尔排序",
                "algorithm",
                "希尔排序怎样利用增量分组改善插入排序？",
                "按逐步缩小的增量把记录分组并做插入排序，最终用增量 1 完成整体有序。",
                "给定增量序列 d1>d2>…>1，每一趟对下标相差 d 的子序列分别进行直接插入排序，使远距离逆序提前消除。其性能依赖增量序列，常用序列的精确复杂度不可一概而论；算法通常原地，但相等记录可能跨组移动，所以不稳定。",
                "像先按较大跨度把人粗略调整，再缩短步长细排，最后相邻整理。",
                ["Shell sort", "increment sorting"],
                ["shell-sort", "sorting-analysis-applications"],
                ["cs408-direct-insertion-sort"],
            ),
            topic(
                "quick-partition",
                "快速排序的划分",
                "mechanism",
                "一次快速排序划分怎样把枢轴放到最终位置？",
                "选择枢轴并双向或单向扫描，把较小和较大记录分到两侧，再返回子区间边界。",
                "经典双向划分先保存枢轴，左右指针向中间移动：从右找小于枢轴者填左侧空位，再从左找大于枢轴者填右侧空位，指针相遇时放回枢轴。不同划分方案对相等元素和返回边界的约定不同，递归区间必须与所用方案严格匹配。",
                "像用一个门槛把队伍分流，低于门槛去一侧、高于门槛去另一侧，最后门槛本身落位。",
                ["partition", "pivot"],
                ["quick-sort"],
                ["cs408-sorting-concepts"],
            ),
            topic(
                "quick-sort-analysis",
                "快速排序与复杂度分析",
                "algorithm",
                "快速排序的划分平衡程度怎样决定复杂度？",
                "递归划分子区间；划分接近平衡时为 O(n log n)，持续极端失衡时退化为 O(n²)。",
                "快速排序完成一次 O(n) 划分后递归处理左右子区间。平均和最好时间为 O(n log n)，最坏 O(n²)；递归栈平均 O(log n)、最坏 O(n)。随机或三数取中选枢轴可降低持续失衡风险。跨区交换使其通常不稳定，但缓存局部性好，常用于内部排序。",
                "像不断把一堆任务分成两组：每次接近对半时层数少，若总分成一个和其余全部则会形成长链。",
                ["quicksort", "quick sort complexity"],
                ["quick-sort", "sorting-analysis-applications"],
                ["cs408-quick-partition", "cs408-complexity-estimation"],
            ),
            topic(
                "heap-sort",
                "堆排序",
                "algorithm",
                "堆排序怎样反复选择极值并原地完成排序？",
                "先建最大堆，再反复把堆顶与末尾交换并向下调整剩余堆。",
                "升序堆排序把数组建成最大堆，堆顶最大值与当前末尾交换后缩小堆边界，再对根做下滤恢复堆序。自底向上建堆为 O(n)，之后 n-1 次调整各 O(log n)，总时间在最好、平均和最坏均为 O(n log n)，辅助空间 O(1)，通常不稳定。",
                "像冠军树每轮把当前冠军送到领奖区，再从剩余选手中恢复新的冠军。",
                ["heap sort", "堆排序下滤"],
                ["heap-sort", "sorting-analysis-applications"],
                ["cs408-heap-operations"],
            ),
            topic(
                "merge-sort",
                "二路归并排序",
                "algorithm",
                "二路归并排序怎样合并两个有序序列？",
                "递归或迭代地把相邻有序段两两归并，比较段首并依次写入辅助数组。",
                "合并两个有序段时用两个指针选择较小记录写入临时区，再复制剩余部分。自顶向下递归分半或自底向上按段长倍增，都需 O(n log n) 时间；数组实现通常需要 O(n) 辅助空间。相等时先取左段可保持稳定。",
                "像把两列已经按身高排好的人合成一列，每次比较两列队首。",
                ["merge sort", "two-way merge"],
                ["merge-sort", "sorting-analysis-applications"],
                ["cs408-sorting-concepts"],
            ),
            topic(
                "radix-sort",
                "基数排序",
                "algorithm",
                "基数排序怎样按关键字各位完成非比较排序？",
                "按最低位优先或最高位优先，对每一位进行稳定分配和收集，逐位形成整体次序。",
                "LSD 基数排序从最低有效位开始，把记录稳定地分配到 r 个桶并按桶序收集，重复 d 位后有序，时间 O(d(n+r))，辅助空间 O(n+r)。它依赖关键字能拆成有限位和稳定的逐位过程，不受比较排序 Ω(n log n) 下界约束。",
                "像先按个位把号码分箱并保持箱内顺序，再按十位分箱，低位次序会被稳定保留。",
                ["radix sort", "LSD sorting"],
                ["radix-sort", "sorting-analysis-applications"],
                ["cs408-sorting-concepts"],
            ),
            topic(
                "comparison-sorting-lower-bound",
                "比较排序的下界",
                "theorem",
                "为什么一般比较排序最坏至少需要 Ω(n log n) 次比较？",
                "比较排序的决策树至少要有 n! 个叶子，树高因此不小于 log₂(n!)=Ω(n log n)。",
                "把比较排序表示成二叉决策树，每次关键字比较产生至多两个分支。n 个互异元素有 n! 种可能排列，正确算法必须能区分它们，因此叶子数至少 n!，最坏比较次数至少为树高 ⌈log₂(n!)⌉，由 Stirling 估计得到 Ω(n log n)。该结论不约束利用数字位或取值范围的非比较排序。",
                "像用是非问题辨认 n! 种排列，问题数至少足以编码这么多答案。",
                ["sorting lower bound", "decision tree"],
                ["sorting-analysis-applications"],
                ["cs408-asymptotic-notation", "cs408-sorting-concepts"],
            ),
            topic(
                "sorting-method-selection",
                "内部排序算法的比较与选择",
                "comparison",
                "怎样结合规模、初始有序性、稳定性和空间选择排序算法？",
                "选择排序算法要同时考虑时间界、辅助空间、稳定性、数据分布、记录移动成本和实现约束。",
                "小规模或基本有序数据适合插入排序；要求平均高效且可接受最坏退化时可用快速排序；要求稳定并能提供 O(n log n) 时间时可用归并排序；空间紧且需要最坏 O(n log n) 可选堆排序；有限位整数可考虑基数排序。实际选择不能只背复杂度表，还应考虑外存、缓存和记录体积。",
                "像选择运输方式，需要同时看距离、时限、容量、成本和道路条件。",
                ["sorting selection", "排序算法比较"],
                ["sorting-analysis-applications"],
                ["cs408-direct-insertion-sort", "cs408-quick-sort-analysis", "cs408-heap-sort", "cs408-merge-sort"],
            ),
            topic(
                "external-sorting-runs",
                "外部排序与初始归并段",
                "concept",
                "当待排序数据无法全部装入内存时，外部排序怎样组织处理？",
                "先分批读入内存形成有序初始归并段，再通过多趟外存归并得到最终有序文件。",
                "外部排序的主要成本是块读写而非内存比较。基本流程先把每批能装入内存的记录内部排序并写成有序归并段，再反复把若干段合并。减少初始段数量、增加有效归并路数和缩短归并趟数可显著降低 I/O。",
                "像仓库无法一次摊开全部货单，先分桌整理成小册，再把多本有序小册逐轮合成总册。",
                ["external sorting", "initial run"],
                ["external-sort"],
                ["cs408-merge-sort"],
            ),
            topic(
                "k-way-external-merge",
                "多路平衡归并",
                "algorithm",
                "k 路归并如何影响外部排序的归并趟数与内部选择成本？",
                "每趟同时合并 k 个有序段可减少趟数，但需要更多输入缓冲并高效选择当前最小记录。",
                "若初始归并段数为 r，理想 k 路平衡归并约需 ⌈log_k r⌉ 趟。每一路需要输入缓冲，另需输出缓冲；若线性比较 k 个段首会增加 CPU 成本，可用败者树把每次选择降到 O(log k)。实际路数受内存缓冲和设备并行能力限制。",
                "像同时汇总多本有序名册，开的桌子越多轮次越少，但每桌都要占空间并需要快速判断当前最小条目。",
                ["k-way merge", "balanced merge"],
                ["external-sort"],
                ["cs408-external-sorting-runs"],
            ),
            topic(
                "loser-tree",
                "败者树",
                "mechanism",
                "败者树怎样加速多路归并中的最小记录选择？",
                "败者树保存比较败者，根外保留胜者；某一路更新后只需沿到根的路径重新比较。",
                "败者树是一棵用于 k 路归并的完全二叉比较结构，内部结点记录比较中的败者，最终胜者单独保存。输出胜者后，仅该输入路读入新记录并沿其叶到根重新比赛，选择新胜者需 O(log k) 次比较；哨兵可表示某一路已经耗尽。",
                "像淘汰赛记住每轮落败者，冠军换人后只需重赛其晋级路径。",
                ["loser tree", "tournament tree"],
                ["external-sort"],
                ["cs408-k-way-external-merge"],
            ),
            topic(
                "replacement-selection",
                "置换选择生成初始归并段",
                "algorithm",
                "置换选择怎样让初始归并段平均长于内存容量？",
                "利用内存中的选择树持续输出不小于当前段末记录的最小值，暂时冻结不满足条件的输入记录。",
                "内存先装入一批记录，每次输出仍可接在当前有序段后的最小记录，并用新输入替换它；若新记录小于刚输出值，就冻结到下一段。当前可用记录全部冻结时结束本段并解冻。随机输入下初始段平均长度可接近内存记录数的两倍，但不保证固定倍数。",
                "像边发放按号排好的票边补入新票，号码太小的先放到下一批。",
                ["replacement selection", "run generation"],
                ["external-sort"],
                ["cs408-loser-tree"],
            ),
            topic(
                "optimal-merge-tree",
                "最佳归并树",
                "theorem",
                "长度不等的初始归并段怎样安排合并顺序以减少总 I/O？",
                "把各段长度作为叶权构造 Huffman 型最佳归并树，让较短段更早、更深地参与合并。",
                "归并树的带权路径长度等于各初始段在多趟归并中被读写的累计规模。二路情形按 Huffman 原理每次合并最短的两个段可使总成本最小；k 路情形需补入权为 0 的虚段，使叶子数满足 (n-1) mod (k-1)=0，再构造 k 叉最佳归并树。",
                "像合并文件时先拼小文件，避免大文件在许多轮里被反复搬运。",
                ["optimal merge tree", "optimal merging"],
                ["external-sort", "sorting-analysis-applications"],
                ["cs408-huffman-tree", "cs408-external-sorting-runs"],
            ),
        ],
    },
]


def section_id_for(chapter_id: str, concept_id: str) -> str:
    """把原子知识点稳定归入章节内的教学小节。"""
    slug = concept_id.removeprefix("cs408-")
    if chapter_id == "408-basic-concepts":
        return (
            "cs408-basic-data-structure"
            if slug in {"data-terms", "logical-storage-operations", "abstract-data-type"}
            else "cs408-basic-algorithm"
        )
    if chapter_id == "408-linear-lists":
        if slug in {"linear-list-definition", "linear-list-basic-operations"}:
            return "cs408-linear-list-basics"
        if slug.startswith("sequential-list"):
            return "cs408-linear-list-sequential"
        if slug in {
            "singly-linked-list",
            "linked-list-insertion-deletion",
            "doubly-linked-list",
            "circular-linked-list",
        }:
            return "cs408-linear-list-linked"
        return "cs408-linear-list-applications"
    if chapter_id == "408-stacks-queues-arrays":
        if slug.startswith("queue-") or slug in {
            "linked-queue",
            "circular-queue",
            "queue-fifo",
        }:
            return (
                "cs408-stack-queue-applications"
                if slug == "queue-applications"
                else "cs408-queue-basics"
            )
        if slug.startswith("multidimensional") or "matrix" in slug:
            return "cs408-array-storage"
        if slug in {"parentheses-matching", "expression-evaluation", "recursion-stack"}:
            return "cs408-stack-queue-applications"
        return "cs408-stack-basics"
    if chapter_id == "408-trees":
        if slug in {"tree-terms", "tree-properties"}:
            return "cs408-tree-basics"
        if slug in {
            "tree-storage",
            "forest-binary-tree-conversion",
            "tree-forest-traversal",
        }:
            return "cs408-tree-forest"
        if slug in {
            "huffman-tree",
            "huffman-coding",
            "disjoint-set",
            "union-find-optimization",
            "heap-definition",
            "heap-operations",
        }:
            return "cs408-tree-applications"
        return "cs408-binary-tree"
    if chapter_id == "408-graphs":
        if slug in {"graph-definition", "graph-terms"}:
            return "cs408-graph-basics"
        if slug in {
            "adjacency-matrix",
            "adjacency-list",
            "orthogonal-list",
            "adjacency-multilist",
            "graph-storage-comparison",
        }:
            return "cs408-graph-storage"
        if slug in {"depth-first-search", "breadth-first-search", "graph-traversal-complexity"}:
            return "cs408-graph-traversal"
        return "cs408-graph-applications"
    if chapter_id == "408-searching":
        if slug in {"search-concepts", "average-search-length", "search-method-selection"}:
            return "cs408-search-basics"
        if slug.startswith("hash"):
            return "cs408-hash-search"
        if slug in {
            "brute-force-string-matching",
            "kmp-prefix-function",
            "kmp-matching",
            "next-nextval",
        }:
            return "cs408-string-search"
        if slug in {
            "binary-search-tree",
            "bst-search-insert",
            "bst-delete",
            "bst-asl",
            "avl-balance",
            "avl-insertion",
            "avl-deletion",
            "red-black-properties",
            "red-black-operations",
            "b-tree-definition",
            "b-tree-search",
            "b-tree-insertion",
            "b-tree-deletion",
            "b-plus-tree",
            "b-tree-vs-b-plus",
        }:
            return "cs408-tree-search"
        return "cs408-linear-search"
    if chapter_id == "408-sorting":
        if slug == "sorting-concepts":
            return "cs408-sorting-basics"
        if slug in {
            "external-sorting-runs",
            "k-way-external-merge",
            "loser-tree",
            "replacement-selection",
            "optimal-merge-tree",
        }:
            return "cs408-external-sorting"
        if slug in {"comparison-sorting-lower-bound", "sorting-method-selection"}:
            return "cs408-sorting-analysis"
        return "cs408-internal-sorting"
    raise ValueError(f"未知章节：{chapter_id}")


def main() -> None:
    official_by_id = dict(OFFICIAL_ITEMS)
    if len(official_by_id) != len(OFFICIAL_ITEMS):
        raise ValueError("考纲叶子条目 ID 重复")

    kb = ROOT / "knowledge_base"
    taxonomy_path = kb / "authoring" / "taxonomies" / f"{COURSE_ID}.json"
    if not taxonomy_path.exists():
        raise FileNotFoundError(
            "请先运行 seed_408_exam_guide_authoring.py，建立 408 课程与考纲指南章节。"
        )
    taxonomy = read_json(taxonomy_path)
    generated_chapter_ids = {chapter["id"] for chapter in CHAPTERS}
    taxonomy["chapters"] = [
        chapter
        for chapter in taxonomy.get("chapters", [])
        if chapter["id"] not in generated_chapter_ids
    ]

    coverage: dict[str, list[str]] = {item_id: [] for item_id, _ in OFFICIAL_ITEMS}
    total_concepts = 0
    chapter_manifests: list[str] = []
    chapter_order_start = max(
        (chapter.get("order", 0) for chapter in taxonomy["chapters"]),
        default=0,
    )

    for chapter_offset, chapter_spec in enumerate(CHAPTERS, start=1):
        chapter_id = chapter_spec["id"]
        section_defs = chapter_spec["sections"]
        section_ids = {section_id for section_id, _, _ in section_defs}
        taxonomy["chapters"].append({
            "id": chapter_id,
            "title": chapter_spec["title"],
            "title_zh": chapter_spec["title_zh"],
            "order": chapter_order_start + chapter_offset,
            "source_chapter_number": chapter_offset,
            "sections": [
                {
                    "id": section_id,
                    "title": title,
                    "title_zh": title_zh,
                    "order": section_order,
                    "source_section_number": f"{chapter_offset}.{section_order}",
                    "subsections": [],
                    "concept_ids": [],
                }
                for section_order, (section_id, title, title_zh)
                in enumerate(section_defs, start=1)
            ],
        })

        records: list[dict[str, Any]] = []
        concepts: list[dict[str, Any]] = []
        visualization_candidates: list[dict[str, Any]] = []
        plan_sections: dict[str, list[dict[str, Any]]] = {
            section_id: [] for section_id in section_ids
        }
        for order, spec in enumerate(chapter_spec["topics"], start=1):
            section_id = section_id_for(chapter_id, spec["id"])
            if section_id not in section_ids:
                raise ValueError(f"{spec['id']} 被分配到未知小节 {section_id}")
            unknown_covers = set(spec["covers"]) - official_by_id.keys()
            if unknown_covers:
                raise ValueError(f"{spec['id']} 引用了未知考纲条目：{sorted(unknown_covers)}")
            for item_id in spec["covers"]:
                coverage[item_id].append(spec["id"])

            source_id = f"syllabus-note-{spec['id']}"
            source_content = (
                f"{spec['summary']}\n\n{spec['definition']}\n\n"
                f"对应 2026 数据结构考纲叶子条目："
                + "、".join(official_by_id[item_id] for item_id in spec["covers"])
                + "。"
            )
            records.append({
                "id": source_id,
                "type": "paragraph",
                "content": source_content,
                "content_format": "markdown",
                "language": "zh",
                "document_order": order,
                "heading_path": [
                    "2026 408 数据结构完整考纲知识",
                    chapter_spec["title_zh"],
                    next(title_zh for sid, _, title_zh in section_defs if sid == section_id),
                ],
                "source_title": "2026 408 数据结构考纲知识整理",
                "source_sha256": REPORT_SHA256,
                "source_urls": SOURCE_URLS,
            })
            plan_sections[section_id].append({
                "temporary_id": f"{chapter_id}-candidate-{order:03d}",
                "proposed_title": spec["title"],
                "core_question": spec["question"],
                "content_type": spec["content_type"],
                "source_record_ids": [source_id],
                "reason_for_separation": (
                    "该知识点具有独立定义、操作过程或分析结论，"
                    "可在 3～8 分钟内独立讲清并单独检索。"
                ),
            })

            keywords = list(dict.fromkeys([spec["title"], *spec["aliases"]]))
            is_visual = spec["content_type"] in {"algorithm", "mechanism"}
            concepts.append({
                "id": spec["id"],
                "title": spec["title"],
                "aliases": spec["aliases"],
                "content_type": spec["content_type"],
                "location": {
                    "course_id": COURSE_ID,
                    "chapter_id": chapter_id,
                    "section_id": section_id,
                    "parent_id": None,
                    "order": order,
                },
                "core_question": spec["question"],
                "summary": spec["summary"],
                "definition": spec["definition"],
                "prerequisite_ids": spec["prerequisites"],
                "relations": [{
                    "type": "part_of",
                    "target_id": chapter_spec["guide_id"],
                    "description": (
                        f"{spec['title']}是"
                        f"{chapter_spec['title_zh']}考纲模块中的原子知识点。"
                    ),
                }],
                "rookie_explanation": {
                    "analogy": spec["intuition"],
                    "mapping": {
                        "直观对象": spec["title"],
                        "对应机制": spec["summary"],
                    },
                    "boundary": (
                        "类比只用于建立直觉；正式作答仍需使用定义、操作步骤、"
                        "适用条件和复杂度结论。"
                    ),
                },
                "retrieval": {
                    "keywords": keywords,
                    "query_examples": [
                        spec["question"],
                        f"{spec['title']}的步骤、性质和复杂度是什么？",
                        f"{spec['title']}有哪些适用条件和易错边界？",
                    ],
                },
                "visualization_ids": VISUALIZATION_BINDINGS.get(spec["id"], []),
                "source_record_ids": [source_id],
                "quality": {"status": "review_pending", "issues": []},
                "version": 2 if spec["id"] in VISUALIZATION_BINDINGS else 1,
            })
            visualization_candidates.append({
                "concept_id": spec["id"],
                "recommended": is_visual,
                "priority": "medium" if is_visual else "low",
                "suggested_type": "algorithm_execution" if is_visual else "structure_layout",
                "reason": (
                    "该知识点包含可逐步演示的结构变化或算法过程，适合进入课件候选评审。"
                    if is_visual
                    else "该知识点当前以文字、公式或比较表表达更直接。"
                ),
                "possible_scenes": (
                    [f"{spec['title']}初始状态", f"{spec['title']}关键步骤与结果"]
                    if is_visual
                    else []
                ),
            })

        plan = {
            "chapter": chapter_id,
            "sections": [
                {
                    "section_id": section_id,
                    "proposed_concepts": plan_sections[section_id],
                }
                for section_id, _, _ in section_defs
            ],
        }
        manifest = {
            "source_id": f"cs408-2026-syllabus-{chapter_id}",
            "source_filename": "deep-research-report.md",
            "sha256": REPORT_SHA256,
            "imported_at": "2026-07-25",
            "scope": (
                f"2026 408 数据结构考纲之“{chapter_spec['title_zh']}”全部叶子条目"
            ),
            "verification_urls": SOURCE_URLS,
            "covered_official_item_ids": sorted({
                item_id
                for spec in chapter_spec["topics"]
                for item_id in spec["covers"]
            }),
            "provenance_note": (
                "用户报告提供范围和学习建议；公开 2026 考纲 PDF 用于逐条复核目录。"
                "本脚本据标准教材口径写成原子知识内容，等待内容审查。"
            ),
            "review_status": "review_pending",
        }
        write_json_atomic(kb / "authoring" / "plans" / f"{chapter_id}.json", plan)
        write_json_atomic(
            kb / "authoring" / "source_manifests" / f"{chapter_id}.json",
            manifest,
        )
        write_jsonl_atomic(
            kb / "authoring" / "sources" / f"{chapter_id}.jsonl",
            records,
        )
        write_jsonl_atomic(
            kb / "authoring" / "drafts" / f"{chapter_id}.jsonl",
            concepts,
        )
        write_jsonl_atomic(
            kb / "authoring" / "viz" / f"{chapter_id}.jsonl",
            visualization_candidates,
        )
        total_concepts += len(concepts)
        chapter_manifests.append(chapter_id)

    taxonomy["chapters"].sort(key=lambda chapter: chapter["order"])
    write_json_atomic(taxonomy_path, taxonomy)

    uncovered = sorted(item_id for item_id, concept_ids in coverage.items() if not concept_ids)
    coverage_artifact = {
        "version": 1,
        "course_id": COURSE_ID,
        "syllabus": "2026 全国硕士研究生招生考试计算机学科专业基础考试大纲：数据结构",
        "verified_at": "2026-07-25",
        "official_leaf_count": len(OFFICIAL_ITEMS),
        "content_concept_count": total_concepts,
        "chapter_ids": chapter_manifests,
        "items": [
            {
                "item_id": item_id,
                "title": title,
                "concept_ids": coverage[item_id],
            }
            for item_id, title in OFFICIAL_ITEMS
        ],
        "uncovered_item_ids": uncovered,
        "source_urls": SOURCE_URLS,
        "review_status": "review_pending",
    }
    write_json_atomic(
        kb / "authoring" / "coverage" / "408-data-structures-2026.json",
        coverage_artifact,
    )
    if uncovered:
        raise ValueError(f"仍有未覆盖考纲条目：{uncovered}")
    print(
        f"已生成 {total_concepts} 个 408 数据结构内容知识点，"
        f"覆盖 {len(OFFICIAL_ITEMS)} / {len(OFFICIAL_ITEMS)} 个考纲叶子条目。"
    )


if __name__ == "__main__":
    main()
